import type { EndingId, StoryQuest } from './narrative-data';
import type { LocalizedText } from './types';
import { chapter, choice as a, evidence as e, residents, t, talk } from './faction-story-shared';

export const VILLAIN_QUESTS: StoryQuest[] = [
  chapter('villain-own-standard', null, t('I. Under My Own Standard', 'I. Под собственным знаменем'),
    t('You rule the Old Fort in Frostspine. Ren brings accounts, not orders. A royal shipment can supply your advance on the palace, but your former freight agent Raut has hidden something among the barley.',
      'Ты правишь Старым фортом в Инейном хребте. Рен приносит счета, не приказы. Королевский обоз может снабдить твоё наступление на дворец, но бывший обозный распорядитель Раут спрятал кое-что среди ячменя.'),
    t('The Old Fort has armed retainers and no settled campaign. Other rulers still decide which road its wagons may use.',
      'В Старом форте есть вооружённые дружинники, но направление похода не выбрано. Пока другие властители решают, по какой дороге поедут его телеги.'),
    [
      talk('ren', t('Hear Ren’s report in your Old Fort.', 'Выслушать доклад Рена в своём Старом форте.'),
        t('Your people are assembled. The crown expects us to remain a mountain nuisance; I assume you intend to disappoint it. We can take its shipment intact once the escort is beaten. First, a warning: Raut used your old freight authority to move black panels under barley. Mara’s previous drivers disappeared. Learn what we are taking before we put it inside your walls.',
          'Твои люди собрались. Корона рассчитывает, что мы останемся горной помехой; полагаю, ты намерен её разочаровать. Можно забрать обоз целиком, разбив охрану. Но сперва предупреждение: Раут по твоим старым обозным полномочиям вёз чёрные пластины под ячменём. Прежние возчики Мары исчезли. Узнай, что берём, прежде чем втаскивать за собственные стены.'),
        [a('villain-fort-council', t('I choose the targets. Bring me the freight trail, not a royal employment offer.', 'Цели выбираю я. Дай мне след грузов, не предложение королевского найма.'),
          t('I took command of my own mountain campaign. Ren is my adviser and wheelwright; Mara is a neutral owner whose information I need, not my paymaster.',
            'Я принял командование собственным горным походом. Рен — мой советник и колёсник; Мара — независимая хозяйка, чьи сведения мне нужны, не моя нанимательница.'),
          t('Roadward first. She has the drivers’ identifying records. Try letting her finish a sentence before deciding its price.',
            'Сперва Трактовый двор. У неё опознавательные записи возчиков. Дай ей закончить фразу, прежде чем назначать цену.'))]),
      talk('mara', t('Demand an account of the hidden freight from Mara.', 'Потребовать у Мары объяснения скрытого груза.'),
        t('Demand what you like; I did not sell Raut the men beneath his paperwork. Three carts returned, barley untouched, drivers missing, black glass underneath. Here are their token numbers and scars. Toman saw the first man answer his dead wife at the orchard. His bell brought the horses back. I own these wagons. Your quarrel with the crown does not transfer the deeds.',
          'Требуй сколько угодно; людей под бумагами Раута я ему не продавала. Вернулись три телеги: ячмень цел, возчиков нет, снизу чёрное стекло. Вот номера жетонов и шрамы. Томан видел, как первый у сада ответил умершей жене. На его колокол вернулись лошади. Повозки мои. Твоя ссора с короной купчие не передаёт.'),
        [a('villain-driver-names', t('I claim the royal shipment, not your title to every cart. I will inspect the orchard.', 'Я претендую на королевский обоз, не на все твои телеги. Осмотрю сад.'),
          t('Mara supplied the identifying records without submitting to the Old Fort. The military shipment and her independent property are separate claims.',
            'Мара дала опознавательные записи, не подчинившись Старому форту. Военный обоз и её независимое имущество — разные притязания.'),
          t('Then distinguish them when you are holding a sword, too. The tracks are beyond Greenhollow’s salt.',
            'Тогда различай и с мечом в руке. Следы за соляной полосой Зелёной лощины.'))]),
      e('villain', 'names-stones'),
      talk('ren', t('Choose your irreversible campaign of dominion or plunder.', 'Необратимо выбрать поход за властью или добычей.'),
        t('A burial tag, not ordinary contraband. The Caller borrows dead voices; answering draws people out. Loose glass did not save those men. Choose where the living royal shipment will go after we defeat its guards. Dominion means taking and supplying palace and quarry, delivering the prize to the palace post. Plunder means taking and supplying the palace post but bringing the prize back to the Old Fort. Either course ends against the Palace Marshal at the royal citadel.',
          'Погребальная бирка, не обычная контрабанда. Оклик берёт голоса мёртвых; ответ выманивает людей. Несобранное стекло их не спасло. Реши, куда пойдёт целый королевский обоз после разгрома охраны. Власть: взять и снабдить дворцовый пост и карьер, доставить добычу к дворцовому посту. Добыча: взять и снабдить дворцовый пост, но вернуть груз в Старый форт. Оба пути ведут к схватке с Дворцовым маршалом в королевской цитадели.'),
        [
          a('villain-claim-dominion', t('Dominion. Hold palace and quarry; make the captured shipment supply my advance.', 'Власть. Удержим дворцовый пост и карьер; взятый обоз снабдит моё наступление.'),
            t('I chose dominion: capture and supply palace and quarry, appropriate the living shipment and deliver it to the palace post before defeating the Palace Marshal. I mean to hold what I take.',
              'Я выбрал власть: взять и снабдить дворцовый пост и карьер, присвоить целый обоз и доставить его к дворцовому посту до победы над Дворцовым маршалом. Я намерен удерживать взятое.'),
            t('Then your reach grows with your obligations. The quarry will need supplies as surely as the palace. Sella at Mirecross can trace the burial tag.',
              'Тогда вместе с владениями растут обязательства. Карьеру нужны припасы не меньше, чем дворцовому посту. Селла в Болотном броде проследит погребальную бирку.'),
            { directive: 'dominion', reputation: { registry: 1, commons: -2 } }),
          a('villain-claim-plunder', t('Plunder. Supply the palace foothold, but bring the living prize to my mountain walls.', 'Добыча. Снабдим дворцовый плацдарм, но целый трофей доставим к моим горным стенам.'),
            t('I chose plunder: take and supply the palace post, bring the appropriated living shipment back to the Old Fort, then defeat the Palace Marshal. Quarry occupation is not required.',
              'Я выбрал добычу: взять и снабдить дворцовый пост, вернуть присвоенный целый обоз в Старый форт, затем победить Дворцового маршала. Занятие карьера не требуется.'),
            t('A long return with a prize worth following. Your own walls, your own appetite. Take the chapel trail through Mirecross.',
              'Долгий возврат с добычей, за которой стоит погнаться. Твои стены, твой аппетит. След часовни идёт через Болотный брод.'),
            { directive: 'plunder', reputation: { commons: -1, registry: -2 } }),
        ]),
    ]),
  chapter('villain-unbought-witnesses', 'villain-own-standard', t('II. Witnesses I Do Not Own', 'II. Свидетели, которые мне не принадлежат'),
    t('Trace Raut’s hidden trade through neutral river and coastal communities. A ruler can seize a box; making its contents tell a convenient story is another matter.',
      'Проследить тайную торговлю Раута через независимые речные и береговые общины. Властитель может забрать ящик; заставить содержимое рассказать удобную историю — другое дело.'),
    t('The freight accounts still let Raut present his monopoly as a service performed for the Old Fort.',
      'По грузовым счетам Раут всё ещё может представлять свою монополию услугой Старому форту.'),
    [
      talk('sella', t('Question Sella about the chapel crate.', 'Расспросить Селлу о ящике часовни.'),
        t('The color of my coat does not make me your retainer. I work this river. A chapel crate broke on the Drowned Archive steps; the packing is still there. Bring back facts if you want to dispute a freight account. Bringing more soldiers will not change the weight.',
          'Цвет моего кафтана не делает меня твоей дружинницей. Я работаю на этой реке. Ящик часовни разбился на ступенях Затопленного архива; упаковка там. Принеси факты, если хочешь оспорить грузовой счёт. От лишних солдат вес не изменится.'),
        [a('villain-river-witness', t('I need the crate, not an invented oath. Show me the safe approach.', 'Мне нужен ящик, не выдуманная присяга. Покажи безопасный подход.'),
          t('Sella gave evidence without accepting my rule. The river remains a neutral community, not another company under my banner.',
            'Селла дала сведения, не признав мою власть. Речная община независима, не ещё один отряд под моим знаменем.'),
          t('Avoid the third step. It refuses everyone equally.', 'Обойди третью ступень. Она всем одинаково отказывает.'))]),
      e('villain', 'river-plates'),
      talk('ivet', t('Ask what authority took the chapel’s dead.', 'Узнать, по чьей власти забрали мёртвых часовни.'),
        t('Raut called it emergency ward-making. Your old freight authority appears beside crown forms in the returns. He took salt, then opened graves. I will keep the remaining consignment here. You can let me circulate the full tally naming his patron, or leave it under witness seal while you trace the buyer. Do not ask me to write that your mountain walls had nothing to do with this.',
          'Раут назвал это срочным изготовлением защиты. В возвратах твои старые обозные полномочия стоят рядом с коронными бланками. Он взял соль, потом вскрыл могилы. Оставшуюся партию я не отдам. Могу разослать полную опись с именем его покровителя или оставить под свидетельской печатью, пока ищешь покупателя. Только не проси написать, будто твои горные стены здесь ни при чём.'),
        [
          a('villain-account-public', t('Circulate it. My claim to rule will have to survive my name on the page.', 'Рассылай. Моему притязанию на власть придётся выдержать моё имя на странице.'),
            t('I allowed the chapel to circulate the full account of Raut’s use of my authority. I did not gain innocence by exposing a former agent.',
              'Я позволил часовне разослать полное описание того, как Раут пользовался моей властью. Разоблачение бывшего распорядителя не сделало меня невиновным.'),
            t('Then Orsa gets the whole tally, too. The remaining salt stays at this threshold.', 'Тогда и Орсе полная опись. Остаток соли остаётся на этом пороге.'),
            { reputation: { commons: 2, lanterns: 1, registry: -1 } }),
          a('villain-account-sealed', t('Keep independent sealed copies. I want the buyer before the public accusation.', 'Оставь независимые запечатанные копии. Сперва покупатель, потом открытое обвинение.'),
            t('I asked for delayed publication while independent witnesses retained the evidence. Raut’s victims must wait; control of the timing serves my campaign as well as the inquiry.',
              'Я потребовал отложить оглашение, оставив улики независимым свидетелям. Жертвы Раута ждут; контроль над сроком служит моему походу не меньше, чем дознанию.'),
            t('Sealed, not rewritten. Orsa receives the quantities now. I do not promise to keep your secret forever.',
              'Запечатано, не переписано. Орсе количества передам сейчас. Вечно хранить твою тайну не обещаю.'),
            { reputation: { registry: 2, commons: -2, lanterns: -1 } }),
        ]),
      talk('orsa', t('Trace the buyer through Saltmarket.', 'Проследить покупателя через Соляной торг.'),
        t('I will not sell you a neat distinction between Raut’s profits and the power that opened his doors. The Tide Observatory has a broken panel and a sling that carried twice the declared barley weight. Check them. Buying the road does not make the accounts disappear.',
          'Я не продам тебе аккуратной границы между прибылями Раута и властью, открывавшей ему двери. В Приливной башне есть разбитая пластина и стропа, поднявшая вдвое больше заявленного ячменя. Проверь. Покупка дороги не уничтожает счета.'),
        [a('villain-coast-weights', t('The accounts stay. I want to know what power he was buying.', 'Счета останутся. Хочу знать, какую власть он покупал.'),
          t('I followed the unloading evidence instead of replacing Raut’s story with my own declaration. The buyer’s mark can establish his private operation.',
            'Я пошёл по следам разгрузки, не заменяя рассказ Раута собственным заявлением. Клеймо покупателя может установить его частную операцию.'),
          t('And the maker’s mark leads inland. Neither is impressed by titles.', 'А клеймо мастера ведёт вглубь страны. Титулы ни на одно не действуют.'))]),
      e('villain', 'winter-tides'),
    ]),
  chapter('villain-price-of-command', 'villain-unbought-witnesses', t('III. The Price of Command', 'III. Цена власти'),
    t('See what Raut built under your former authority, then confront the palace records. The ward trade is useful power, but taking it unchanged would leave you dependent on its captive machinery.',
      'Увидеть, что Раут построил под твоими прежними полномочиями, затем проверить дворцовые записи. Торговля защитой даёт полезную власть, но принять её неизменной — значит зависеть от её пленного устройства.'),
    t('Raut’s accounts still promise effortless control. Nobody has shown what that promise makes others carry.',
      'Счета Раута всё ещё обещают власть без усилий. Никто не показал, какой груз это обещание возлагает на других.'),
    [
      talk('beran', t('Make Beran explain the glass you could inherit.', 'Потребовать у Берана объяснить стекло, которое может достаться тебе.'),
        t('I made the panes. Fitted around a wagon, they work. Bone ash, burial salt and bell bronze hold dead voices that resist the Caller. Loose cargo does not protect its drivers. Raut wanted exclusive supply and charged to cross the danger his requisitions made worse. You could take the books. You would also take the need to keep feeding the furnace.',
          'Пластины делал я. Собранные вокруг повозки, работают. Костяной пепел, погребальная соль и колокольная бронза держат голоса мёртвых, которые противятся Оклику. Просто груз возчиков не защищает. Раут хотел исключительных поставок и брал плату за переход опасности, усугублённой его изъятиями. Можешь забрать книги. Заберёшь и необходимость кормить печь.'),
        [a('villain-foundry', t('Show me the test. I will not call dependence on a furnace sovereignty.', 'Покажи испытание. Зависимость от печи суверенностью не назову.'),
          t('Beran confirmed the glass works by imprisoning the dead. Raut’s monopoly offered command of passage while depending on continued extraction from graves.',
            'Беран подтвердил: стекло работает заточением мёртвых. Монополия Раута давала власть над проходом, но зависела от дальнейшего изъятия из могил.'),
          t('The quarry keeps the frames and signed test tally. My name stays with the rejects.', 'В карьере каркасы и подписанный журнал испытания. На браке моё имя.'))]),
      e('villain', 'winter-glass'),
      talk('vesk', t('Meet Vesk under limited safe conduct at Crownbridge.', 'Встретиться с Веском по ограниченному перемирию у Коронного моста.'),
        t('Our truce covers this inquiry, not your advance on the palace. Raut’s freight papers crossed my stores and carried authority he first obtained from you. I kept the complaints and broken ward parts in the Sealed Vault. Inspect them. Proving his scheme does not make your assault lawful in my eyes.',
          'Перемирие касается дознания, не твоего наступления на дворец. Бумаги Раута шли через мои склады и несли полномочия, впервые полученные от тебя. Жалобы и сломанные части защиты я оставил в Опечатанном подвале. Осмотри. Доказанная схема не сделает твой штурм законным в моих глазах.'),
        [a('villain-vault-access', t('I did not come for your permission to rule. I will read the records.', 'Я не за разрешением править пришёл. Прочту записи.'),
          t('Vesk granted limited access to evidence while remaining an opposing garrison commander. Neither side exchanged allegiance or pardoned the other.',
            'Веск дал ограниченный доступ к уликам, оставаясь командиром противостоящего гарнизона. Ни одна сторона не сменила верность и не простила другую.'),
          t('Then we understand the limit. Copies go to civilian witnesses as well as your fort.', 'Значит, предел понятен. Копии пойдут гражданским свидетелям, не только в твой форт.'))]),
      e('villain', 'weight-order'),
      talk('ren', t('Decide what to do with the freight authority Raut used.', 'Решить судьбу обозных полномочий, которыми пользовался Раут.'),
        t('He read the complaints and renewed the taking for his own profit. He was your agent, not your equal, and used the space you left him. You can renounce the old requisition authority in a declaration copied outside the fort, or keep the authority while publishing his signed deviations from it. The second preserves a weapon for your rule. It also preserves the excuse another agent will use.',
          'Он прочёл жалобы и продлил изъятия ради своей прибыли. Он был твоим распорядителем, не ровней, и воспользовался оставленным ему простором. Можешь отречься от старых реквизиционных полномочий в заявлении с копиями вне форта. Или сохранить полномочия, огласив подписанные им отступления. Второй путь оставляет тебе оружие власти. И оправдание следующему распорядителю.'),
        [
          a('villain-revoke-writ', t('Renounce that writ. I will take territory openly, not claim the dead as freight.', 'Откажусь от этих полномочий. Земли возьму открыто, мёртвых грузом не объявлю.'),
            t('I publicly renounced the old burial-requisition authority Raut used. This limits one instrument of my rule; it does not cancel my military ambition or absolve my earlier delegation.',
              'Я открыто отказался от прежних полномочий на погребальные изъятия, которыми пользовался Раут. Это ограничивает один инструмент власти, но не отменяет военных притязаний и не оправдывает прежнее поручение.'),
            t('Copies leave today. A declaration does not arrest Raut or empty his stores; it prevents you calling the old paper harmless.',
              'Копии уйдут сегодня. Заявление не арестует Раута и не опустошит его склады. Зато не даст тебе объявить старую бумагу безобидной.'),
            { reputation: { commons: 2, lanterns: 2, registry: -1 } }),
          a('villain-retain-writ', t('Publish his deviations. Retain my authority over living military supply.', 'Огласим его отступления. Мою власть над живым военным снабжением сохраним.'),
            t('I retained my claim to requisition living military supplies while exposing Raut’s use of graves and private fees. The distinction is public, but leaves broad power in my own hands.',
              'Я сохранил притязание на реквизицию живых военных припасов, огласив использование Раутом могил и личных сборов. Различие заявлено открыто, но широкая власть остаётся у меня.'),
            t('Then the witnesses keep both texts. Whoever suffers the next levy will compare them. Nika at High Pass carried the warning he refused.',
              'Тогда у свидетелей оба текста. Пострадавшие от следующего побора их сравнят. Ника на Высоком перевале несла отвергнутое им предупреждение.'),
            { reputation: { registry: 2, commons: -2, lanterns: -1 } }),
        ]),
    ]),
  chapter('villain-a-power-not-borrowed', 'villain-price-of-command', t('IV. A Power Not Borrowed', 'IV. Власть не взаймы'),
    t('Find out what can replace Raut’s glass without surrendering your campaign to the crown. The Old Fort’s ruler must choose obligations as well as enemies.',
      'Узнать, чем заменить стекло Раута, не отдав свой поход короне. Правителю Старого форта предстоит выбирать не только врагов, но и обязательства.'),
    t('The palace remains an enemy, and the old binding remains a power no title can order to change.',
      'Дворец остаётся врагом, а старая привязь — силой, которой ни один титул не прикажет измениться.'),
    [
      talk('nika', t('Hear Nika near your mountain domain.', 'Выслушать Нику у своих горных владений.'),
        t('The pass is not yours because your fort overlooks it. I guided the courier who warned Raut. He read the letter, then asked how much freight his glass could cover. On the way back she answered her dead brother. I held her coat until she stopped stepping off the path. A commander may order silence; grief does not salute. Lev has the old fittings and the warning at Star Monastery.',
          'Перевал не твой оттого, что форт над ним. Я вела гонца с предупреждением Рауту. Он прочёл письмо и спросил, сколько груза укроет стекло. Обратно она ответила покойному брату. Я держала её за полы, пока она не перестала сходить с тропы. Командир может приказать молчать; горе честь не отдаёт. У Льва в Звёздном монастыре старые детали и предупреждение.'),
        [a('villain-pass-warning', t('I will inspect the old work. I have no use for a defense that depends on pretending men do not grieve.', 'Осмотрю старое устройство. Защита, притворяющаяся, будто люди не горюют, мне не нужна.'),
          t('Nika established Raut’s knowledge and the Caller’s ability to draw a living listener away. Her rescued courier proves that an answer is not itself a death sentence.',
            'Ника подтвердила осведомлённость Раута и способность Оклика уводить живого слушателя. Спасённая гонец доказывает: сам ответ не смертный приговор.'),
          t('Then keep someone beside your proudest soldier. He may need a hand before he admits it.', 'Тогда поставь кого-нибудь рядом с самым гордым бойцом. Рука понадобится раньше, чем он признает.'))]),
      e('villain', 'weight-census'),
      talk('ren', t('Confirm your march against the royal citadel.', 'Подтвердить поход против королевской цитадели.'),
        t('The sketches offer three maintained bell watches, a willing confined keeper, or broken glass with no replacement shelter. None hands you effortless mastery. Radek must cast three bells and Yara must find willing, fed watches for the first. Your military order remains yours: deliver the seized living shipment to the palace under dominion, or bring it back here under plunder; supply the required holdings, then defeat the Palace Marshal at the royal citadel. Raut’s guilt is no substitute for that victory.',
          'По чертежам возможны три обслуживаемых дозора, добровольный заточённый смотритель или разбитое стекло без нового укрытия. Беззаботного всевластия не даёт ни один. Для первого Радек должен отлить три колокола, а Яра найти сытые добровольные дозоры. Военный приказ остаётся твоим: при власти доставь присвоенный целый обоз к дворцу, при добыче верни сюда; снабди требуемые владения, затем победи Дворцового маршала в королевской цитадели. Вина Раута победу не заменит.'),
        [a('villain-final-command', t('The citadel is my target. No crown commission will settle this campaign.', 'Моя цель — цитадель. Коронным назначением этот поход не закончится.'),
          t('I confirmed the chosen campaign and the Palace Marshal as the final military enemy. Raut’s papers remain in independent hands; his fate is not settled by this march.',
            'Я подтвердил выбранный поход и Дворцового маршала как последнего военного врага. Бумаги Раута остаются в независимых руках; этот поход не решает его судьбу.'),
          t('Ada in Hollow Village has the last drivers’ records. Finish the inquiry before deciding what the victory is allowed to conceal.',
            'У Ады в Глухой деревне последние записи о возчиках. Закончи дознание, прежде чем решать, что победе позволено скрыть.'))]),
    ]),
  chapter('villain-the-victors-road', 'villain-a-power-not-borrowed', t('V. The Victor’s Road', 'V. Тракт победителя'),
    t('Identify the dead and examine the anchor, then enact a settlement only after your chosen campaign defeats the Palace Marshal. Victory gives you force, not a different set of physical ward laws.',
      'Опознать мёртвых и осмотреть привязь, затем исполнить решение лишь после победы выбранного похода над Дворцовым маршалом. Победа даёт силу, но не меняет устройство защиты.'),
    t('The anchor still holds its captives. Neither a claim on the palace nor a promise of a new order has opened it.',
      'Привязь всё ещё держит пленников. Ни притязание на дворец, ни обещание нового порядка её не разомкнули.'),
    [
      talk('ada', t('Ask Ada to identify the dead brought with Raut’s freight.', 'Попросить Аду опознать мёртвых, привезённых с грузом Раута.'),
        t('Three dead drivers arrived with requisition freight from the Old Orchard. I buried them; tokens and notes are beside the covered Echo Well. I did not bury them as your subjects or the crown’s. If you want to know who they were, compare Mara’s records. If you want the well to praise you, it will find a voice you like. Do not answer.',
          'С реквизиционным грузом из Старого сада привезли троих мёртвых возчиков. Я похоронила; жетоны и записи у закрытого Колодца эха. Не хоронила ни твоими подданными, ни коронными. Хочешь знать, кто они, — сверь записи Мары. Хочешь похвал от колодца — он найдёт приятный тебе голос. Не отвечай.'),
        [a('villain-hollow-witness', t('Give me the records. I will not count a borrowed voice as an oath.', 'Дай записи. Заимствованный голос за присягу не приму.'),
          t('Ada’s notes may identify the drivers. The voices beneath the lid prove neither survivors nor consent to any ruler.',
            'Записи Ады могут опознать возчиков. Голоса под крышкой не доказывают ни наличия выживших, ни согласия на чью-либо власть.'),
          t('Walk inside Elin’s salt marks. Your title does not widen them.', 'Иди внутри соляных отметок Элина. Титул их не раздвинет.'))]),
      e('villain', 'road-names'),
      e('villain', 'road-index'),
      talk('mara', t('Return the confirmed records without claiming the wages.', 'Вернуть подтверждённые записи, не присваивая жалованье.'),
        t('All three match. I will pay their families from the purses I kept. You can conquer the palace and still owe an answer about a freight agent who once worked with your authority. Finding the dead is one answer, not the whole account.',
          'Все трое совпали. Заплачу семьям из сохранённых кошелей. Можно завоевать дворец и всё ещё отвечать за распорядителя, работавшего по твоим полномочиям. Найти мёртвых — один ответ, не полный расчёт.'),
        [a('villain-wages-home', t('The purses remain theirs. My campaign does not inherit their pay.', 'Кошели остаются их. Мой поход не наследует их жалованье.'),
          t('Mara confirmed the three deaths and retained the records and wages for the families. The precise cause of death remains unproven, and my former authority remains in the evidence.',
            'Мара подтвердила гибель троих, оставив записи и жалованье семьям. Точная причина смерти не доказана, а мои прежние полномочия остаются в уликах.'),
          t('Then leave me to write to them. Elin is waiting for a ruler to hear a limit.', 'Тогда дай мне написать им. Элин ждёт властителя, способного выслушать пределы.'))]),
      talk('elin', t('After defeating the Palace Marshal, settle the binding.', 'После победы над Дворцовым маршалом решить судьбу привязи.'),
        t('Complete your campaign first: the live shipment delivered to its chosen destination, the required holdings supplied, the Palace Marshal beaten. Then three willing, maintained watches can replace the anchor if Radek and Yara have made them possible. I may volunteer to bear it, but no conquest constitutes my consent. Or release the dead without replacement and lose the glass shelter. Your victory does not add a fourth mechanism.',
          'Сперва закончи поход: целый обоз доставлен к выбранной цели, нужные владения снабжены, Дворцовый маршал побеждён. Тогда три добровольных обслуживаемых дозора заменят привязь, если Радек и Яра их подготовили. Я могу предложить себя, но завоевание не заменит моего согласия. Или отпусти мёртвых без замены и потеряй стеклянное укрытие. Твоя победа четвёртого устройства не добавляет.'),
        [
          a('villain-ending-commons', t('Accept independent watches. A road with limits is worth more to my rule than Raut’s monopoly.', 'Приму независимые дозоры. Дорога с пределами для моей власти ценнее монополии Раута.'),
            t('After my military victory I accepted three independent watches as a limit on my control of passage. The dead are released only after Radek’s bells and Yara’s willing keepers take over.',
              'После своей военной победы я принял три независимых дозора как предел власти над проходом. Мёртвых отпускают только после вступления колоколов Радека и добровольцев Яры.'),
            t('Then they may halt your wagons too. We agree on the bells, not on every claim your banner makes.',
              'Тогда и твои телеги они вправе остановить. Мы согласны насчёт колоколов, не насчёт каждого притязания твоего знамени.'),
            { ending: 'commons', gate: 'conquest', requiresActions: ['villain-bell-mourn', 'villain-stag-dependents'], reputation: { commons: 2, lanterns: 2, registry: -1 } }),
          a('villain-ending-compact', t('Take the binding by your own offer. I will provision the cloister, but cannot own your consent.', 'Прими привязь по своему предложению. Я снабжу скит, но твоим согласием владеть не могу.'),
            t('After conquest I accepted Elin’s voluntary confinement and the continuing obligation to provision him. My realm gains a central ward; its keeper is not a transferable prize.',
              'После завоевания я принял добровольное заточение Элина и постоянную обязанность снабжать его. Владения получают центральную защиту; её смотритель не передаваемый трофей.'),
            t('I consent with the limits understood. Candlekeepers keep access and supplies of their own. Your generosity must not become the only door.',
              'Я согласен, понимая пределы. Свечники сохранят свой доступ и запасы. Твоя щедрость не должна стать единственной дверью.'),
            { ending: 'compact', gate: 'conquest', reputation: { registry: 3, commons: -2, lanterns: 1 } }),
          a('villain-ending-cinder', t('Break the monopoly and the glass together. I accept an exposed road no rival can buy from Raut.', 'Разобьём и монополию, и стекло. Приму опасный тракт, который соперник не купит у Раута.'),
            t('After conquest I ordered the prepared binding broken without a replacement. It frees the dead and denies every rival the same glass advantage, while exposing ordinary travelers as well.',
              'После завоевания я велел разбить подготовленную привязь без замены. Это освобождает мёртвых и лишает соперников стеклянного преимущества, одновременно подвергая опасности обычных путников.'),
            t('Then do not name it a gift without naming the cost. Clear the road before opening the anchor; soldiers cannot command the dark to retreat.',
              'Тогда не называй это даром, умолчав о цене. Освободи тракт до размыкания: солдаты не прикажут темноте отступить.'),
            { ending: 'cinder', gate: 'conquest', reputation: { lanterns: 2, registry: -2, commons: -1 } }),
        ]),
    ]),
];

export const VILLAIN_ENDINGS: Record<EndingId, LocalizedText> = {
  commons: t('A Throne with Three Limits', 'Трон с тремя пределами'),
  compact: t('The Keeper and the Conqueror', 'Смотритель и завоеватель'),
  cinder: t('No Rival’s Glass', 'Стекло не достанется сопернику'),
};

export const VILLAIN_EPILOGUES: Record<EndingId, LocalizedText> = {
  commons: t(
    'The Palace Marshal is defeated at the royal citadel. The appropriated shipment has reached the destination you chose, and your required holdings stand supplied. You remain the ruler of the Old Fort, not a rewarded servant of the crown. Radek’s three bells reach Yara’s willing watches; Elin releases the dead only when every bell answers. Independent communities keep the ropes and can stop even your wagons when a watch fails. Ren calls the bargain a durable road, not a surrender. Some retainers call it three small refusals a conqueror ought not tolerate. You tolerate them because reliable passage serves your power better than Raut’s furnace monopoly. Mara pays the drivers’ families, and their records still carry the history of your former agent.',
    'Дворцовый маршал побеждён в королевской цитадели. Присвоенный обоз доставлен к выбранной тобой цели, необходимые владения снабжены. Ты остаёшься правителем Старого форта, не награждённым слугой короны. Три колокола Радека доходят до добровольных дозоров Яры; Элин отпускает мёртвых только после ответа каждого. Независимые общины держат верёвки и могут остановить даже твои телеги, если дозор не вышел. Рен называет договор надёжной дорогой, не капитуляцией. Некоторые дружинники — тремя мелкими отказами, которых завоевателю терпеть не следует. Ты терпишь: надёжный проход полезнее твоей власти, чем печная монополия Раута. Мара платит семьям возчиков; в их записях остаётся история твоего бывшего распорядителя.'),
  compact: t(
    'Your military campaign succeeds against the Palace Marshal; the live prize is delivered and the chosen holdings are supplied. Elin freely closes the wrist-piece and releases the dead. Your standards now travel under a ward centered on one man who cannot pass the cloister gate. You provision him and gain the reputation of a ruler who can make roads work. Candlekeepers keep another key and a separate store; without them every petition could become a request for your favor. Ren records the upkeep beside the revenues, refusing to call the keeper spoils. Mara pays the three families. Raut’s papers survive in independent hands: conquering a palace has not rewritten the authority that once helped him.',
    'Твой поход заканчивается победой над Дворцовым маршалом: целый трофей доставлен, выбранные владения снабжены. Элин свободно замыкает обруч и отпускает мёртвых. Твои знамёна теперь идут под защитой, сосредоточенной на человеке, который не может выйти за ворота скита. Ты снабжаешь его и получаешь славу правителя, способного наладить дороги. У Свечников другой ключ и отдельный запас; без них любая просьба могла бы стать просьбой о твоей милости. Рен записывает расходы на содержание рядом с доходами, не называя смотрителя добычей. Мара платит трём семьям. Бумаги Раута остаются в независимых руках: завоевание дворца не переписало историю власти, когда-то помогавшей ему.'),
  cinder: t(
    'The Palace Marshal falls and your chosen military claims are fulfilled. Behind supplied holdings, with the living shipment safely delivered, the crews clear the road and break the anchor. The dead leave. No rival can purchase Raut’s glass advantage now, and no captive replaces it. Your soldiers can take a tollhouse but cannot order the Caller away from an exposed cart. Freight moves in daylight, fees rise and two distant hamlets empty before winter. The Old Fort gains an enemy’s defeat, not command of the night. Mara pays the drivers’ families and refuses to call their loss part of your triumph. You have destroyed a rival source of power. The people who must travel through what remains will decide what else to call it.',
    'Дворцовый маршал пал, выбранные военные притязания исполнены. За снабжёнными владениями, после безопасной доставки целого обоза, рабочие освобождают дорогу и разбивают привязь. Мёртвые уходят. Ни один соперник теперь не купит стеклянного преимущества Раута; нового пленника вместо него нет. Твои солдаты могут взять сборный двор, но не прикажут Оклику отойти от открытой телеги. Грузы идут засветло, плата растёт, до зимы два дальних хутора пустеют. Старый форт получает поражение врага, не власть над ночью. Мара платит семьям возчиков и отказывается считать их потерю частью твоего торжества. Ты уничтожил соперничающий источник власти. Люди, которым ехать через оставшееся, сами решат, как ещё это назвать.'),
};

export const VILLAIN_NPCS = residents('villain', {
  mara: {
    greeting: t('A mountain ruler at my door. The yard is neutral, and the wagons are not a tribute.', 'Горный властитель у моей двери. Двор независимый, повозки не дань.'),
    localQuestion: t('What will you recognize as mine?', 'Что ты признаешь моим?'),
    local: t('What you own, and what the military operation actually takes. Not every neutral human road stop is a conquered province. Your order seizes a living royal shipment after its guards are beaten; where you take it depends on the command you gave Ren.',
      'То, чем владеешь, и то, что действительно взял военным действием. Не каждая независимая людская стоянка — завоёванная провинция. Твой приказ — присвоить целый королевский обоз после разгрома охраны; куда его вести, зависит от распоряжения Рену.'),
    reactions: [{ after: 'villain-road-names', text: t('The dead have names now. Neither your victory nor Raut’s excuses will replace them.', 'Теперь у погибших есть имена. Ни твоя победа, ни оправдания Раута их не заменят.') }],
  },
  toman: {
    greeting: t('Your fort has stone walls; ours are wood. That does not make our doors yours to open.', 'У твоего форта стены каменные, у нас деревянные. От этого наши двери не тебе открывать.'),
  },
  lida: { greeting: t('If you want fruit, speak to the owner. If you want to talk, hold this twine without pulling.', 'За плодами — к хозяйке. Хочешь поговорить — держи бечёвку, не тяни.') },
  yara: { greeting: t('My hunters are not unclaimed recruits. If you need willing watches, learn what willingness costs.', 'Мои охотники не бесхозные новобранцы. Нужны добровольные дозоры — узнай цену добровольности.') },
  sella: { greeting: t('We may wear similar colors. I still own my boat and choose my work.', 'Цвета одежды могут совпасть. Лодка всё равно моя, работу выбираю сама.') },
  ivet: { greeting: t('Your title waits outside with your weapons. Inside, the sick take precedence.', 'Титул ждёт с оружием снаружи. Внутри первыми будут больные.') },
  oss: { greeting: t('A mountain fort cannot order this river level down. Wait for my signal to board.', 'Горный форт уровень реки не понизит. На борт — по моему знаку.') },
  orsa: { greeting: t('Conquest changes who asks for credit. It does not change how much grain is in a sack.', 'Завоевание меняет просителя в долг. Количества зерна в мешке не меняет.') },
  dren: { greeting: t('If you came for a share, first learn whose ship it was. We have enough disputed claims.', 'Если пришёл за долей, сперва узнай, чьё судно. Спорных притязаний и так хватает.') },
  hana: { greeting: t('The shore light serves ships, including ones you dislike. Leave its bearing alone.', 'Береговой огонь служит судам, в том числе неприятным тебе. Направление не трогай.') },
  beran: { greeting: t('My work bears my stamp, not an oath to your fort. Ask what it does before claiming it.', 'На работе моё клеймо, не присяга твоему форту. Сперва спроси, как работает, потом забирай.') },
  tessa: { greeting: t('Poisoned water will not spare your retainers. Help me compare these samples.', 'Отравленная вода дружинников не пощадит. Помоги сравнить пробы.') },
  vesk: {
    name: t('Commander Vesk', 'Командир Веск'), role: t('Crownbridge garrison commander', 'Командир гарнизона Коронного моста'),
    greeting: t('Safe conduct for this conversation. Outside it, I still serve the palace you intend to take.', 'На этот разговор — безопасный проход. За его пределами я служу дворцу, который ты намерен взять.'),
    localQuestion: t('Why open the vault to an opposing ruler?', 'Зачем открывать подвал противнику?'),
    local: t('Civilian claims to returned goods and testimony do not cease because armies face one another. Our limited truce protects this inquiry. The Palace Marshal at the royal citadel remains your military opponent; I have not surrendered him or my allegiance.',
      'Гражданские права на возвращённое имущество и показания не исчезают оттого, что армии противостоят друг другу. Ограниченное перемирие защищает дознание. Дворцовый маршал в королевской цитадели остаётся твоим военным противником; ни его, ни свою верность я не сдавал.'),
    beliefQuestion: t('Will you serve whoever wins the citadel?', 'Будешь служить тому, кто возьмёт цитадель?'),
    belief: t('An office can change hands. An oath is something the person who made it must answer for. I will not offer you mine as a bargaining chip.',
      'Должность может перейти в другие руки. За присягу отвечает давший её человек. Свою я тебе как разменную монету не предложу.'),
  },
  radek: { greeting: t('The bronze is already spoken for under witnessed terms. Your arrival does not melt those terms.', 'На бронзу уже есть условия при свидетелях. От твоего прихода они не расплавятся.') },
  nika: { greeting: t('You can see your fort from here. You still need a guide on this side of the ridge.', 'Отсюда видно твой форт. На этой стороне хребта всё равно нужен проводник.') },
  lev: { greeting: t('Read the old instructions. They were here before your title and may outlast it.', 'Прочти старые наставления. Они были до твоего титула и могут его пережить.') },
  ada: { greeting: t('Around the salt, not over it. No ruler has yet improved that instruction.', 'Вокруг соли, не через неё. Ни один правитель ещё не улучшил это наставление.') },
  mila: { greeting: t('You may command a fort. This coat belongs to someone who asked me not to cut it down.', 'Ты можешь командовать фортом. Этот кафтан принадлежит человеку, который просил не ушивать.') },
  elin: {
    greeting: t('If you came to own the binding, first learn what owning it would require of a living person.', 'Если пришёл владеть привязью, сперва узнай, чего такое владение потребует от живого человека.'),
    localQuestion: t('What limits remain after I defeat the palace?', 'Какие пределы останутся после моей победы над дворцом?'),
    local: t('All the ward’s limits. Your directive’s holdings must be supplied, the appropriated shipment delivered alive and the Palace Marshal defeated before the operation. Three bells need three maintained voluntary watches. A living binding needs informed consent and confines its keeper. Breaking it without replacement ends glass protection.',
      'Все пределы защиты. До работы снабди требуемые приказом владения, доставь присвоенный обоз целым и победи Дворцового маршала. Трём колоколам нужны три обслуживаемых добровольных дозора. Живая привязь требует осознанного согласия и заточает смотрителя. Разлом без замены прекращает защиту стекла.'),
  },
  ren: {
    locationId: 'old-fort', name: t('Ren the Cartwright', 'Рен Тележник'),
    role: t('Fort adviser and master of wagons', 'Советник форта и обозный мастер'),
    activity: t('Checking campaign loads beside the fort’s wheel bench', 'Проверяет походные грузы у колёсного верстака форта'),
    greeting: t('Your fort, your orders. My job is to tell you which axle will break under them.', 'Твой форт, твои приказы. Моё дело — сказать, какая ось под ними сломается.'),
    localQuestion: t('Where does the seized shipment go under my command?', 'Куда по моему приказу пойдёт взятый обоз?'),
    local: t('Dominion sends the living prize to the palace post and requires palace and quarry held and supplied. Plunder brings it back to the Old Fort after the palace foothold is supplied. In both, defeat the escort before taking the shipment; do not destroy the cart. Your final enemy is the Palace Marshal at the royal citadel.',
      'При власти целый трофей идёт к дворцовому посту; нужны взятые и снабжённые дворцовый пост и карьер. При добыче возвращаем сюда, снабдив дворцовый плацдарм. В обоих случаях сперва разгроми охрану, не уничтожай телегу. Последний враг — Дворцовый маршал в королевской цитадели.'),
    beliefQuestion: t('Will you contradict me in front of the retainers?', 'Станешь возражать мне при дружинниках?'),
    belief: t('About a hot hub, yes. About a march that cannot be supplied, also yes. If all you wanted was agreement, you could have promoted a mirror.',
      'Насчёт горячей втулки — да. Насчёт похода без снабжения — тоже. Если нужно лишь согласие, мог повысить зеркало.'),
    reactions: [
      { after: 'villain-claim-dominion', text: t('Dominion is the order. Palace and quarry need your supplies; the living prize goes to the palace post.', 'Приказ — власть. Дворцовому посту и карьеру нужны твои припасы; целый трофей идёт к дворцовому посту.') },
      { after: 'villain-claim-plunder', text: t('Plunder is the order. Supply the palace foothold and bring the living prize back to these mountain walls.', 'Приказ — добыча. Снабди дворцовый плацдарм и верни целый трофей к этим горным стенам.') },
    ],
  },
});
