import type { EndingId, StoryQuest } from './narrative-data';
import type { LocalizedText } from './types';
import { chapter, choice as a, evidence as e, residents, t, talk } from './faction-story-shared';

export const GUARD_QUESTS: StoryQuest[] = [
  chapter('guard-empty-relief', null, t('I. The Relief That Did Not Arrive', 'I. Смена, которая не пришла'),
    t('You serve the palace guard under Commander Vesk at Crownbridge. A threatened supply shipment, a missing civilian crew and hostile movements have left your comrades waiting at the palace post.',
      'Ты служишь в дворцовой страже под началом командира Веска у Коронного моста. Обоз под угрозой, гражданские возчики пропали, противник движется — твои товарищи на дворцовом посту всё ещё ждут смены.'),
    t('The palace post remains on short relief. Vesk has not issued your operational assignment.',
      'Дворцовому посту всё ещё не хватает смены. Веск пока не выдал тебе оперативное назначение.'),
    [
      talk('vesk', t('Report to Commander Vesk at Crownbridge.', 'Явиться к командиру Веску у Коронного моста.'),
        t('You are on my strength, not Mara’s payroll. Our post is threatened by Raut’s advance; elven partisans also watch the requisition road. We protect the palace and the people keeping its gates, not every order somebody stamps. Mara’s previous three drivers vanished. Take their descriptions at Roadward, examine the orchard and report before I assign the column.',
          'Ты в моём списке, не на жалованье у Мары. Нашему посту грозит наступление Раута; эльфийские партизаны тоже следят за реквизиционной дорогой. Мы защищаем дворец и людей у его ворот, не любой приказ с печатью. Трое прежних возчиков Мары пропали. Возьми приметы на Трактовом дворе, осмотри сад и доложи, прежде чем я назначу отряд.'),
        [a('guard-report', t('Understood. I will establish what happened before naming an enemy.', 'Есть. Сперва установлю, что случилось, потом назову врага.'),
          t('Vesk ordered an inquiry before deployment. I remain under the Crownbridge chain of command; Mara is a civilian witness.',
            'Веск приказал провести дознание до выступления. Я остаюсь в подчинении Коронного моста; Мара — гражданская свидетельница.'),
          t('And bring back your people. An elegant report is no use to the empty beds in the barracks.',
            'И людей своих верни. Красивый доклад пустым койкам в казарме ни к чему.'))]),
      talk('mara', t('Take the drivers’ identifying records from Mara.', 'Взять у Мары приметы возчиков.'),
        t('Uniforms loaded my wagons; now a uniform asks where the men went. Here are their token numbers and scars. The carts returned with untouched barley over hidden black glass. Toman saw the lead driver answer his dead wife at the orchard. A bell brought the horses back. Do not write “partisan abduction” because it fits your morning orders.',
          'Мундиры грузили мои телеги; теперь мундир спрашивает, куда делись люди. Вот номера жетонов и шрамы. Телеги вернулись с нетронутым ячменём над спрятанным чёрным стеклом. Томан видел, как передний возчик у сада ответил умершей жене. На колокол вернулись лошади. Не пиши «похищены партизанами», потому что так удобнее утреннему приказу.'),
        [a('guard-driver-names', t('Your account goes in the report unchanged. I will examine the tracks.', 'Твой рассказ войдёт в доклад без исправлений. Осмотрю следы.'),
          t('Mara supplied identifying records and challenged the assumption of an elven attack. Her drivers’ fate must be established independently.',
            'Мара дала опознавательные записи и оспорила предположение об эльфийском нападении. Судьбу возчиков нужно установить независимо.'),
          t('The orchard lies outside Toman’s tended salt. Mind where you put those regulation boots.',
            'Сад за соляной полосой, за которой следит Томан. Смотри, куда ступаешь уставным сапогом.'))]),
      e('guard', 'names-stones'),
      talk('vesk', t('Receive an irreversible operational order.', 'Получить необратимый оперативный приказ.'),
        t('No struggle, a broken salt line and chapel packing: not enough to blame the forest. The Caller borrows dead voices; no answering it on watch. I authorize two assignments. Relief: repel the palace attackers, supply the post and escort the living shipment there before the fortress sortie. Pursuit adds taking and supplying the quarry to cut their approach. Recommend one; my order will bind the deployment.',
          'Борьбы нет, соль размыта, упаковка часовни: лес обвинять рано. Оклик берёт голоса мёртвых; на посту не отвечать. Разрешаю два назначения. Помощь: отбить дворцовых нападающих, снабдить пост и провести туда целый обоз до вылазки на крепость. Преследование требует ещё взять и снабдить карьер, отрезав подход врага. Предложи одно; мой приказ закрепит назначение.'),
        [
          a('guard-order-relief', t('Recommend relief. Our comrades and the shipment come first.', 'Предлагаю помощь. Сперва товарищи и обоз.'),
            t('Vesk assigned relief: repel the palace attack, supply the palace post and bring the protected shipment there alive, then undertake the fortress sortie. Quarry occupation is not part of this order.',
              'Веск назначил помощь: отбить нападение, снабдить дворцовый пост и привести туда охраняемый обоз целым, затем совершить вылазку на крепость. Занятие карьера в приказ не входит.'),
            t('Relief approved. You are not to destroy the shipment to deny it to the enemy. Follow its chapel freight records through Mirecross while the watch holds.',
              'Помощь утверждаю. Уничтожать обоз, чтобы не достался врагу, запрещаю. Пока дозор держится, проследи записи о грузе часовни через Болотный брод.'),
            { directive: 'relief', reputation: { registry: 2, commons: 1 } }),
          a('guard-order-pursuit', t('Recommend pursuit. Relieve the palace, then take and supply the quarry.', 'Предлагаю преследование. Поможем дворцу, затем возьмём и снабдим карьер.'),
            t('Vesk authorized pursuit. The palace relief and living shipment escort remain mandatory; capture and supply of the quarry are an additional duty before the fortress sortie.',
              'Веск разрешил преследование. Помощь дворцу и сохранение обоза обязательны; захват и снабжение карьера — дополнительный долг до вылазки на крепость.'),
            t('Pursuit approved. A longer front means more comrades depending on your cart. Sella at Mirecross can trace the chapel tag.',
              'Преследование утверждаю. На длинном фронте больше товарищей зависит от твоей телеги. Селла в Болотном броде проследит бирку часовни.'),
            { directive: 'pursuit', reputation: { registry: 3, commons: -1 } }),
        ]),
    ]),
  chapter('guard-sealed-evidence', 'guard-empty-relief', t('II. A Seal Is Not an Answer', 'II. Печать не ответ'),
    t('Follow the freight through the Fens and Salt Coast. Your authority can preserve evidence, but it cannot turn a requisition into consent.',
      'Проследить грузы через Топи и Соляной берег. Твои полномочия могут сохранить улики, но не превратят реквизицию в согласие.'),
    t('The requisition seal still frightens witnesses away from the desk meant to hear them.',
      'Реквизиционная печать всё ещё отпугивает свидетелей от стола, за которым их должны выслушать.'),
    [
      talk('sella', t('Ask Sella to identify the recovered crates.', 'Попросить Селлу опознать поднятые ящики.'),
        t('I will tell you where I found them, not swear that every palace coat is honest. One chapel crate broke on the Drowned Archive steps. The third step will not bear you. If you want a seizure receipt, inspect the contents before writing it.',
          'Расскажу, где нашла, но честность каждого дворцового мундира не заверю. Один ящик часовни разбился на ступенях Затопленного архива. Третья тебя не выдержит. Нужна расписка об изъятии — осмотри содержимое, потом пиши.'),
        [a('guard-river-witness', t('You are a witness, not a suspect for refusing an oath.', 'Ты свидетельница. Отказ присягать не делает тебя подозреваемой.'),
          t('Sella identified the broken crate. I recorded the limits of her testimony rather than treating neutrality as obstruction.',
            'Селла указала разбитый ящик. Я отметил пределы её показаний, не назвав нейтралитет препятствием следствию.'),
          t('Then leave me my pulley. It is not evidence merely because it lifted a box.', 'Тогда оставь мой блок. Поднял ящик — ещё не стал уликой.'))]),
      e('guard', 'river-plates'),
      talk('ivet', t('Record Ivet’s account of the requisitions.', 'Записать рассказ Иветы о реквизициях.'),
        t('Raut’s quartermasters took burial salt and opened graves under emergency papers. Some carried old crown forms. I need the remaining stores at the threshold, and I need their taking recorded somewhere that cannot quietly lose my name. Will you make this an official complaint with a civilian copy, or keep the witnesses confidential in Vesk’s inquiry?',
          'Интенданты Раута по чрезвычайным бумагам забрали погребальную соль и вскрыли могилы. У некоторых были старые коронные бланки. Оставшиеся припасы нужны на пороге, а изъятие нужно записать там, где моё имя не потеряют тихонько. Оформите официальную жалобу с гражданской копией или скроете свидетелей в дознании Веска?'),
        [
          a('guard-public-return', t('Register the complaint and leave an independent copy with the chapel.', 'Зарегистрируем жалобу. Независимая копия останется часовне.'),
            t('Ivet kept her remaining stores and lodged a named complaint with an independent copy. Vesk’s office must now answer a record it cannot withdraw alone.',
              'Ивета оставила припасы и подала именную жалобу с независимой копией. Контора Веска теперь должна ответить на запись, которую не может отозвать в одиночку.'),
            t('Put my name on it. Orsa can compare the quantities against Saltmarket receipts.', 'Моё имя ставь. Орса сверит количества с расписками Соляного торга.'),
            { reputation: { commons: 2, lanterns: 1, registry: -1 } }),
          a('guard-protected-witness', t('Keep identities confidential for now; preserve copies outside the command desk.', 'Пока скроем личности; копии сохраним вне командирского стола.'),
            t('Ivet kept her stores and agreed to confidential testimony. The evidence has independent copies, but public scrutiny of the command must wait.',
              'Ивета оставила припасы и согласилась на закрытые показания. Есть независимые копии, но публичного разбора действий командования пока не будет.'),
            t('Then do not call silence forgiveness. Give Orsa my quantities without the patients’ names.',
              'Только не называй молчание прощением. Передай Орсе количества без имён больных.'),
            { reputation: { registry: 2, lanterns: 1, commons: -1 } }),
        ]),
      talk('orsa', t('Compare the chapel tally with civilian freight.', 'Сравнить опись часовни с гражданскими грузами.'),
        t('The declared barley weight does not match the sling at the Tide Observatory. You can guard a load faithfully and still guard a lie. Check the damaged panel and the buyer’s docket before calling this secure supply.',
          'Заявленный вес ячменя не совпадает со стропой Приливной башни. Можно верно охранять груз и при этом охранять ложь. Проверь повреждённую пластину и накладную покупателя, прежде чем считать снабжение надёжным.'),
        [a('guard-coast-weights', t('The escort order does not exempt the cargo from inspection.', 'Приказ охранять не освобождает груз от досмотра.'),
          t('I took the discrepancy to the unloading evidence. Protecting the shipment does not mean certifying its concealed contents.',
            'Я отправился проверять расхождение по следам разгрузки. Защита обоза не означает одобрения скрытого содержимого.'),
          t('That distinction may keep another driver alive. The sling is on the lower shelf.', 'Это различие может спасти ещё одного возчика. Стропа на нижней полке.'))]),
      e('guard', 'winter-tides'),
    ]),
  chapter('guard-own-signatures', 'guard-sealed-evidence', t('III. Our Own Signatures', 'III. Наши собственные подписи'),
    t('Test the glass evidence and return to your commander. The enemy’s scheme grew through offices that comrades were ordered to trust.',
      'Проверить улики о стекле и вернуться к командиру. Вражеская схема прошла через конторы, которым товарищам приказывали доверять.'),
    t('The garrison cannot know which assurances failed until somebody compares the working glass with the orders that bought it.',
      'Гарнизон не узнает, какие гарантии оказались ложными, пока не сравнят действующее стекло с приказами о его закупке.'),
    [
      talk('beran', t('Ask the founder what the glass protects.', 'Спросить литейщика, от чего защищает стекло.'),
        t('A fitted enclosure protects its occupant; loose panels under grain do not. I made it from burial ash, salt and bell bronze. The dead held inside keep the Caller back. Raut’s men tested two frames at the quarry and ordered more. Your escort can survive behind glass while the villages supplying it lose their wards.',
          'Собранное ограждение защищает сидящего внутри; пластины под зерном — нет. Я делал его из погребального пепла, соли и колокольной бронзы. Запертые мёртвые сдерживают Оклик. Люди Раута испытали два каркаса в карьере и заказали ещё. Твой конвой может выжить за стеклом, пока давшие материал деревни теряют защиту.'),
        [a('guard-foundry', t('I will inspect the test. “It works” does not settle what we may use.', 'Осмотрю испытание. «Работает» ещё не значит «можно пользоваться».'),
          t('Beran described real protection obtained through captivity. The test must distinguish fitted glass from concealed freight and identify who knew the cost.',
            'Беран описал настоящую защиту, полученную через плен. Испытание должно отличить собранное стекло от скрытого груза и показать, кто знал цену.'),
          t('Look at the bare seat, then the inspector’s signature. Both belong in the same report.', 'Посмотри на открытое сиденье, потом на подпись инспектора. В докладе нужны оба.'))]),
      e('guard', 'winter-glass'),
      talk('vesk', t('Report the ward-glass scheme to Vesk.', 'Доложить Веску о схеме с обережным стеклом.'),
        t('I signed allocations for the palace. Raut diverted the emergency freight machinery into his own occupation army and charged for protection he had first stripped from others. I kept returned bell parts with the complaints in the Sealed Vault. Check my records as well as his. That is an order, not an invitation to acquit me.',
          'Я подписывал дворцовые наряды. Раут повернул механизм чрезвычайных перевозок на своё оккупационное войско и брал плату за защиту, которую сперва отнял у других. Возвращённые детали колоколов с жалобами лежат в Опечатанном подвале. Проверь мои записи вместе с его. Это приказ, не предложение меня оправдать.'),
        [a('guard-vault-access', t('I will enter both names and preserve the original returns.', 'Внесу оба имени и сохраню подлинные возвраты.'),
          t('Vesk ordered scrutiny of his own allocations and Raut’s freight operation. Loyalty to the garrison now requires evidence against assumptions made in its name.',
            'Веск приказал проверить свои наряды и обозную операцию Раута. Верность гарнизону теперь требует улик против допущений, сделанных от его имени.'),
          t('Tell the stores watch where the originals go. Their duty does not disappear because ours became uncomfortable.',
            'Сообщи складскому караулу, куда пойдут подлинники. Их долг не исчез оттого, что наш стал неудобен.'))]),
      e('guard', 'weight-order'),
      talk('vesk', t('Set the command’s account before the sortie.', 'Определить отчёт командования до вылазки.'),
        t('He received the village complaints before renewing the taking. My men must hear that before facing him. I can read the evidence on parade and put my signature beside it, or give each section leader the full dossier for a closed briefing until the sortie is over. Both preserve the record. One makes our failure public now; the other asks the ranks to carry another secret.',
          'Он получил деревенские жалобы до продления изъятий. Мои люди должны узнать это, прежде чем идти на него. Могу зачитать улики перед строем и поставить рядом свою подпись. Или выдать командирам отделений полное дело для закрытого разбора до конца вылазки. Запись сохранят оба пути. Первый огласит нашу ошибку сейчас; второй заставит рядовых нести ещё одну тайну.'),
        [
          a('guard-open-muster', t('Request an open muster. The ranks can bear the truth better than another rumor.', 'Прошу открытый сбор. Строй лучше выдержит правду, чем очередной слух.'),
            t('Vesk approved an open muster and put his own signature beside the findings. The garrison heard the evidence before its ordered sortie.',
              'Веск разрешил открытый сбор и поставил свою подпись рядом с выводами. Гарнизон услышал улики до приказанной вылазки.'),
            t('Granted. I will read it, not leave a junior officer to take the shouting. Nika at High Pass carried the warning we still need.',
              'Разрешаю. Читать буду я, не младший офицер под чужие крики. Ника на Высоком перевале несла нужное нам предупреждение.'),
            { reputation: { commons: 2, registry: -1, lanterns: 1 } }),
          a('guard-section-briefing', t('Request section briefings with complete copies. No falsified account to the ranks.', 'Прошу разбор по отделениям с полными копиями. Строю не лгать.'),
            t('Vesk approved closed, complete briefings for the sections. Comrades receive the truth, but civilians must wait for the command’s public account.',
              'Веск разрешил закрытые полные разборы по отделениям. Товарищи узнают правду, но гражданским придётся ждать открытого отчёта командования.'),
            t('Granted. No page disappears from the copies. Find Nika at High Pass; she saw Raut read the warning.',
              'Разрешаю. Из копий ни одной страницы не вынимать. Найди Нику на Высоком перевале: она видела, как Раут читал предупреждение.'),
            { reputation: { registry: 2, commons: -1 } }),
        ]),
    ]),
  chapter('guard-terms-of-duty', 'guard-own-signatures', t('IV. What the Oath Requires', 'IV. Чего требует присяга'),
    t('Find the monastery’s alternatives, then return for the final order. Protecting the palace must not mean lending it another unwilling prisoner.',
      'Найти монастырские способы защиты и вернуться за последним приказом. Защищать дворец — не значит отдавать ему нового невольного пленника.'),
    t('A formation can hold a gate. It cannot replace the missing knowledge of what holds the road.',
      'Строй может удержать ворота. Но не заменит знания о том, что удерживает тракт.'),
    [
      talk('nika', t('Hear the courier’s escort at High Pass.', 'Выслушать проводницу гонца на Высоком перевале.'),
        t('Raut broke the monastery seal in front of me, read the warning and asked only how many wagons the glass covered. On our return the courier answered her dead brother. I held her coat until she stopped climbing off the path. Your regulations need someone close enough to catch a comrade, not merely a rule against answering.',
          'Раут при мне сломал монастырскую печать, прочёл предупреждение и спросил лишь, сколько возов укроет стекло. На обратном пути гонец ответила покойному брату. Я держала её за полы, пока она не перестала лезть с тропы. Твоим уставам нужен человек рядом, способный удержать товарища, не один запрет отвечать.'),
        [a('guard-pass-warning', t('I will carry your account with the monastery copy.', 'Передам твой рассказ вместе с монастырской копией.'),
          t('Nika saw Raut reject the warning and recovered a living listener from the Caller. The testimony establishes intent without claiming every person who answers dies.',
            'Ника видела отказ Раута от предупреждения и удержала живую слушательницу Оклика. Показания устанавливают умысел, не утверждая гибели каждого ответившего.'),
          t('Lev has it at Star Monastery, with the worn fittings that explain the drawings.', 'У Льва в Звёздном монастыре копия и изношенные детали, поясняющие чертежи.'))]),
      e('guard', 'weight-census'),
      talk('vesk', t('Receive the final sortie and ward instructions.', 'Получить указания для последней вылазки и защиты.'),
        t('Your relief or pursuit order stands. Repel the palace attack, supply our post and deliver the living shipment; pursuit also requires the quarry captured and supplied. Then defeat Raut in the authorized fortress sortie. No ward settlement is enacted before that. I authorize you to negotiate three maintained watches, Elin’s free offer, or evacuation of the long stretches before the glass is broken. I do not authorize conscripting a keeper.',
          'Приказ помощи или преследования в силе. Отбей нападение на дворец, снабди наш пост и доставь целый обоз; для преследования ещё возьми и снабди карьер. Затем победи Раута в разрешённой вылазке на крепость. До этого решение о защите не исполняется. Разрешаю договориться о трёх обслуживаемых дозорах, свободном предложении Элина или освобождении дальних перегонов перед разломом стекла. Принудительно назначать смотрителя не разрешаю.'),
        [a('guard-final-orders', t('Orders understood. I will return the people and the evidence, not just the standards.', 'Приказ понятен. Верну людей и улики, не одни знамёна.'),
          t('Vesk confirmed the military obligations and delegated only the ward negotiation. Three watches require Radek’s three bells and Yara’s voluntary households with support for dependents.',
            'Веск подтвердил военные обязанности и поручил только переговоры о защите. Трём дозорам нужны три колокола Радека и добровольцы Яры с обеспечением их близких.'),
          t('Ada in Hollow Village buried the missing drivers. Finish that duty too. Their families are not a footnote to the campaign.',
            'Ада в Глухой деревне похоронила пропавших возчиков. Доведи и этот долг до конца. Их семьи — не примечание к походу.'))]),
    ]),
  chapter('guard-after-the-watch', 'guard-terms-of-duty', t('V. After the Watch Is Relieved', 'V. Когда сменится караул'),
    t('Identify the civilian dead and examine the anchor. After the successful relief and sortie, settle the road’s protection under Vesk’s limited authorization.',
      'Опознать погибших гражданских и осмотреть привязь. После успешной помощи и вылазки устроить защиту тракта в пределах полномочий, данных Веском.'),
    t('The glass remains closed. Neither an order nor a medal can perform the binding work in place of supplied crews.',
      'Стекло остаётся замкнутым. Ни приказ, ни медаль не выполнят работу с привязью вместо снабжённых рабочих.'),
    [
      talk('ada', t('Obtain Ada’s burial records.', 'Получить погребальные записи Ады.'),
        t('Three drivers came dead with requisition freight from the Old Orchard. The records and tokens are beside the covered Echo Well. I want their names returned to families, not filed under acceptable losses. Keep to Elin’s salt marks; the well speaks, but it cannot testify.',
          'Троих возчиков привезли мёртвыми с реквизиционным грузом из Старого сада. Записи и жетоны у закрытого Колодца эха. Хочу вернуть имена семьям, а не вписать в допустимые потери. Иди по соли Элина: колодец говорит, но показаний не даёт.'),
        [a('guard-hollow-witness', t('I will compare the identifying marks and preserve your uncertainty about the cause.', 'Сверю приметы и сохраню твою неуверенность в причине гибели.'),
          t('Ada provided burial evidence. A military report must distinguish identification from an unsupported cause of death.',
            'Ада предоставила погребальные улики. Военный доклад должен различать опознание и недоказанную причину смерти.'),
          t('Then there is room in your report for what you do not know. Good.', 'Значит, в докладе есть место тому, чего ты не знаешь. Хорошо.'))]),
      e('guard', 'road-names'),
      e('guard', 'road-index'),
      talk('mara', t('Give Mara the confirmed identification.', 'Передать Маре подтверждённое опознание.'),
        t('All three match. I will send their pay home myself. No officer will deduct the cost of missing freight from it. You did this under orders; they still needed somebody to do it.',
          'Все трое совпали. Плату сама отправлю домой. Ни один офицер не вычтет из неё стоимость пропавшего груза. Ты исполнил приказ; а им всё равно нужен был человек, который это сделает.'),
        [a('guard-wages-home', t('The records are yours. The wages are not military salvage.', 'Записи твои. Жалованье не военная добыча.'),
          t('Mara confirmed the deaths and took the records for the families. Their wages remain theirs; the manner of death is still not established.',
            'Мара подтвердила гибель и взяла записи для семей. Жалованье остаётся их; обстоятельства смерти всё ещё не установлены.'),
          t('Tell your commander this part is finished. Elin’s work is not.', 'Скажи командиру: эта часть закончена. Работа Элина — нет.'))]),
      talk('elin', t('After the military victory, enact the authorized ward settlement.', 'После военной победы исполнить разрешённое решение о защите.'),
        t('The relief, shipment and sortie must all be complete before this changes. Three bells can replace the anchor if Radek cast three and Yara’s willing watches can feed their dependents. I may freely bind myself instead, confined here for the road. Or we break the glass without replacing it. Vesk can authorize the operation; he cannot make a voice belong to the crown.',
          'Помощь, доставка обоза и вылазка должны завершиться до перемены. Три колокола заменят привязь, если Радек отлил три, а добровольные дозоры Яры могут кормить близких. Вместо этого я могу свободно привязать себя здесь ради тракта. Или разобьём стекло без замены. Веск вправе разрешить работу, но не сделать голос собственностью короны.'),
        [
          a('guard-ending-commons', t('Recognize independent watches. The garrison supports them without owning their ropes.', 'Признаем независимые дозоры. Гарнизон помогает, но не владеет их верёвками.'),
            t('After the successful military operation, the garrison accepted three independent bell watches. Elin releases the dead only after every tended bell answers.',
              'После успешной военной операции гарнизон признал три независимых колокольных дозора. Элин отпускает мёртвых лишь после ответа каждого обслуживаемого колокола.'),
            t('Then a village may stop even a palace wagon when its watch fails. Put that beside the promise of support.',
              'Значит, деревня может остановить даже дворцовую телегу, если дозор не вышел. Запишите рядом с обещанием помощи.'),
            { ending: 'commons', gate: 'conquest', requiresActions: ['guard-bell-mourn', 'guard-stag-dependents'], reputation: { commons: 3, registry: 1 } }),
          a('guard-ending-compact', t('Accept your voluntary service. Keep provisioning and access in separate hands.', 'Примем твою добровольную службу. Снабжение и доступ отдадим разным людям.'),
            t('After victory we accepted Elin’s informed confinement. The garrison provisions a willing keeper, but cannot honestly call his permanent watch an ordinary posting.',
              'После победы мы приняли осознанное заточение Элина. Гарнизон снабжает добровольного смотрителя, но не может честно назвать бессменный дозор обычным назначением.'),
            t('I know the limit of the gate. No officer signs for my visitors alone, and no missed salute stops my bread.',
              'Я знаю, где граница ворот. Ни один офицер не решает о посетителях единолично. За неотданную честь хлеба не лишают.'),
            { ending: 'compact', gate: 'conquest', reputation: { registry: 3, lanterns: 1, commons: -1 } }),
          a('guard-ending-cinder', t('End the captive ward. We will guard daylight routes without claiming the glass still protects them.', 'Прекратим защиту пленниками. Будем охранять дневные пути, не обещая прежнего стеклянного укрытия.'),
            t('After the ordered victory we chose to break the binding without a replacement. Military escort can oppose raiders, not replace the old supernatural shelter.',
              'После приказанной победы мы решили разбить привязь без замены. Военный конвой может противостоять налётчикам, но не заменить прежнее сверхъестественное укрытие.'),
            t('Then clear the exposed routes before we open it. Your comrades need truthful limits more than a proclamation that danger is over.',
              'Тогда освободите опасные перегоны до размыкания. Товарищам важнее знать настоящие пределы защиты, чем услышать, будто опасность кончилась.'),
            { ending: 'cinder', gate: 'conquest', reputation: { lanterns: 3, registry: -2 } }),
        ]),
    ]),
];

export const GUARD_ENDINGS: Record<EndingId, LocalizedText> = {
  commons: t('The Charter of Three Watches', 'Грамота трёх дозоров'),
  compact: t('The Watch Without Relief', 'Караул без смены'),
  cinder: t('An Oath in Daylight', 'Присяга при дневном свете'),
};

export const GUARD_EPILOGUES: Record<EndingId, LocalizedText> = {
  commons: t(
    'The palace assault is repelled, the living shipment delivered and Vesk’s assigned operation completed. Raut is defeated in the ordered sortie. Radek’s three bells and Yara’s willing watches take over before Elin releases the dead. Vesk recognizes their right to halt a military convoy when salt is wet or a rope fails. Some officers call that surrendering authority. The sentries call it a reason to get home. The crown has kept its palace without acquiring every road as property. Mara pays the three families; the garrison records their names without awarding itself credit for their deaths. The charter needs stores, replacements and commanders willing to obey its limits.',
    'Нападение на дворец отбито, целый обоз доставлен, назначенная Веском операция завершена. Раут побеждён в приказанной вылазке. Три колокола Радека и добровольные дозоры Яры принимают защиту до освобождения мёртвых Элином. Веск признаёт их право остановить военный обоз, когда соль промокла или верёвка порвалась. Некоторые офицеры зовут это сдачей власти. Часовые — причиной вернуться домой. Корона сохранила дворец, не получив все дороги в собственность. Мара платит трём семьям; гарнизон записывает имена, не присваивая себе заслугу за их гибель. Грамоте нужны припасы, сменщики и командиры, готовые соблюдать её пределы.'),
  compact: t(
    'Vesk’s order is fulfilled: the palace stands, its shipment survives and Raut falls. With the route secured, Elin freely takes the binding and sends the captive dead away. Palace stores support him, while Candlekeepers retain independent access. For the guards it looks at first like a familiar posting: a gate, a ration, a watch. Then the first relief roster arrives with nobody able to replace his name. Comrades bring news and repair the roof; none can give him leave beyond the worn gate stone. Mara pays the families of her drivers. The road works, and the garrison must live with the difference between honoring a volunteer and making his sacrifice convenient.',
    'Приказ Веска исполнен: дворец стоит, его обоз уцелел, Раут пал. На закреплённом пути Элин свободно принимает привязь и отпускает пленных мёртвых. Дворцовые склады содержат его, а Свечники сохраняют независимый доступ. Для стражников поначалу это похоже на знакомое назначение: ворота, паёк, караул. Потом приходит первое расписание смен, в котором никто не может заменить его имя. Товарищи приносят вести, чинят крышу; никто не может дать отпуск за стёртый камень у ворот. Мара платит семьям возчиков. Тракт работает, а гарнизону приходится различать уважение к добровольцу и привычку удобно пользоваться его жертвой.'),
  cinder: t(
    'The relief succeeds, the shipment reaches the palace alive and the authorized sortie defeats Raut. Only after the road is cleared do the crews break the binding. The dead are released; no conscript is ordered into their place. Vesk signs daylight timetables and accepts that a military seal cannot protect wagons between tended boundaries. Patrols grow longer, leave shorter. A winter delivery turns back, and palace tables lose luxuries before the garrison admits it cannot promise every distant village the same cover. Mara pays the missing drivers’ families and demands honest risk clauses. The guard has kept its oath by naming what it can defend, not by declaring everything defended.',
    'Помощь удалась, обоз дошёл до дворца целым, разрешённая вылазка закончилась победой над Раутом. Только после освобождения тракта рабочие разбивают привязь. Мёртвые отпущены; ни одного новобранца не приказывают поставить вместо них. Веск подписывает дневные расписания и признаёт: военная печать не защищает телеги между обслуживаемыми границами. Дозоры становятся длиннее, увольнения короче. Зимний груз поворачивает назад; дворцовые столы лишаются излишеств, прежде чем гарнизон признаёт, что не обещает одинакового прикрытия каждой дальней деревне. Мара платит семьям пропавших и требует честных условий о риске. Стража сдержала присягу, назвав то, что может защитить, а не объявив защищённым всё.'),
};

export const GUARD_NPCS = residents('guard', {
  mara: {
    greeting: t('Vesk sent you. Then hear a civilian before you write a military explanation.', 'Веск прислал. Тогда выслушай гражданскую, прежде чем писать военное объяснение.'),
    localQuestion: t('Is Roadward part of the palace supply command?', 'Трактовый двор входит в дворцовое снабжение?'),
    local: t('No. This is a neutral human inn and I own my wagons. Your order is to protect the living shipment, not destroy it. Your own supply convoy must feed the palace post; pursuit also requires the quarry.',
      'Нет. Это независимый людской постоялый двор, повозки мои. Твой приказ — сохранить целый обоз, не уничтожить. Твой собственный обоз снабжает дворцовый пост; при преследовании нужен ещё и карьер.'),
    reactions: [{ after: 'guard-road-names', text: t('All three identified. Bring the records, not a wreath from an officer who never learned their names.', 'Все трое опознаны. Принеси записи, не венок от офицера, который их имён не знал.') }],
  },
  toman: {
    greeting: t('We remember the uniforms at our granary. Your safe conduct lets you speak, not command.', 'Мундиры у амбара мы помним. По перемирию ты можешь говорить, не командовать.'),
  },
  lida: { greeting: t('That sword can stay sheathed. The orchard dispute needs a witness, not a formation.', 'Меч пусть будет в ножнах. Саду нужен свидетель, не строй.') },
  yara: { greeting: t('Before you ask who stole a bell, ask who was left without a watch.', 'Прежде чем спрашивать, кто украл колокол, спроси, кого оставили без дозора.') },
  sella: { greeting: t('I have cargo tags, not a loyalty certificate. Which do you actually need?', 'У меня грузовые бирки, не свидетельство верности. Что тебе действительно нужно?') },
  ivet: { greeting: t('Your coat opens no priority bed here. The coldest hands go nearest the stove.', 'Мундир права на лучшую койку не даёт. У печи будут самые холодные руки.') },
  oss: { greeting: t('A command voice will not slow the current. Step where I show you.', 'Командный голос течение не замедлит. Ступай, куда показываю.') },
  orsa: { greeting: t('If the palace needs another load, it needs another honest account of what is inside.', 'Если дворцу нужен ещё груз, нужна и новая честная опись содержимого.') },
  dren: { greeting: t('You can record our names after we finish warming these survivors. They do not wait for a hearing.', 'Имена запишешь, когда выживших отогреем. Они разбора ждать не могут.') },
  hana: { greeting: t('Do not stand between the signal and the sea. Rank does not make you transparent.', 'Не стой между сигналом и морем. Чин прозрачности не придаёт.') },
  beran: { greeting: t('An inspection? Good. Inspect from behind the chalk like everyone else.', 'Досмотр? Хорошо. Осматривай из-за мела, как остальные.') },
  tessa: { greeting: t('If the barracks water tastes wrong, bring a sealed sample, not an order saying it is safe.', 'Если в казарме вода странная, принеси закрытую пробу, не приказ о её безопасности.') },
  vesk: {
    name: t('Commander Vesk', 'Командир Веск'), role: t('Crownbridge garrison commander', 'Командир гарнизона Коронного моста'),
    activity: t('Comparing the relief roster with returned stores', 'Сверяет расписание смен с возвращёнными припасами'),
    greeting: t('Report. If a comrade needs relief, say that before you tell me what went well.', 'Докладывай. Если товарищу нужна смена, скажи прежде, чем рассказывать об успехах.'),
    localQuestion: t('What is my duty at the palace post?', 'В чём мой долг на дворцовом посту?'),
    local: t('It is ours to defend, not yours to capture. Repel the attackers, supply it and escort the living shipment there. If I assigned pursuit, capture and supply the quarry too. The fortress sortie against Raut follows those duties.',
      'Он наш: защищай, не захватывай. Отбей нападающих, снабди и проведи туда целый обоз. При назначенном преследовании ещё возьми и снабди карьер. Вылазка на крепость против Раута идёт после этих обязанностей.'),
    beliefQuestion: t('Can loyalty require a report against our own command?', 'Верность может потребовать доклада против своего командования?'),
    belief: t('Yes. Tell me what failed and who signed it. Concealing a fault until it kills another watch is not comradeship.',
      'Да. Укажи, что не сработало и кто подписал. Прятать ошибку, пока не погибнет другой караул, — не товарищество.'),
    reactions: [
      { after: 'guard-order-relief', text: t('Relief remains your order: defend and supply the palace post, deliver the living shipment, then the fortress sortie.', 'Твой приказ — помощь: защитить и снабдить дворцовый пост, доставить целый обоз, затем вылазка на крепость.') },
      { after: 'guard-order-pursuit', text: t('Pursuit remains your order. The palace and living shipment come first; the quarry must also be captured and supplied before the sortie.', 'Твой приказ — преследование. Сперва дворец и целый обоз; до вылазки нужно также взять и снабдить карьер.') },
    ],
  },
  radek: { greeting: t('A royal request cannot make one bell ring in three villages. We will count the metal first.', 'Королевская просьба не заставит один колокол звенеть в трёх деревнях. Сперва посчитаем металл.') },
  nika: { greeting: t('Your comrade has numb fingers. Warm them before saluting anybody.', 'У твоего товарища пальцы онемели. Отогрейте, прежде чем кому-то честь отдавать.') },
  lev: { greeting: t('We keep copies for a reason. A military seal is not our only memory.', 'Копии храним не зря. Военная печать — не единственная наша память.') },
  ada: { greeting: t('No marching across the salt. Even a burial escort goes around the line.', 'Через соль строем не ходят. Даже погребальная охрана обходит полосу.') },
  mila: { greeting: t('I can mend a uniform. I cannot make its former owner’s promises fit the next person.', 'Мундир починю. Обещания прежнего хозяина на следующего не перешью.') },
  elin: {
    greeting: t('Vesk’s authorization is not consent on my behalf. Ask before you reach for the catch.', 'Разрешение Веска — не согласие от моего имени. Спроси, прежде чем тянуться к защёлке.'),
    localQuestion: t('When may the guard carry out the ward operation?', 'Когда стража может провести работу с защитой?'),
    local: t('After the actual military victory: palace defended and supplied, living shipment delivered, Raut defeated, and the quarry supplied if pursuit was chosen. Three watches also need Radek’s three bells and Yara’s willing keepers. No order replaces any of those.',
      'После настоящей военной победы: дворец защищён и снабжён, целый обоз доставлен, Раут побеждён, а при преследовании снабжён ещё и карьер. Трём дозорам также нужны три колокола Радека и добровольцы Яры. Приказ ничего из этого не заменит.'),
  },
  ren: { greeting: t('Vesk commands the garrison; I decide whether this hub is fit to turn. Hold the wheel.', 'Веск командует гарнизоном; я решаю, годится ли втулка к дороге. Держи колесо.') },
});
