import type { EndingId, StoryQuest } from './narrative-data';
import type { LocalizedText } from './types';
import { chapter, choice as a, evidence as e, residents, t, talk } from './faction-story-shared';

export const ELF_QUESTS: StoryQuest[] = [
  chapter('elf-wooden-walls', null, t('I. Walls That Burn', 'I. Стены, которые горят'),
    t('Greenhollow is your home, not a posting. Palace requisitioners and the mountain lord both claim its stores. Toman needs a partisan leader who can break their supply road without starving the people beside it.',
      'Зелёная лощина — твой дом, а не место службы. На её запасы претендуют и дворцовые сборщики, и горный властитель. Томану нужен предводитель партизан, который оборвёт их снабжение, не уморив людей у тракта.'),
    t('The wooden houses still have their doors barred. No one has settled what the resistance may take in their name.',
      'Двери деревянных домов всё ещё на засовах. Никто не решил, что сопротивление вправе забирать от имени жителей.'),
    [
      talk('toman', t('Hear the village council at Greenhollow.', 'Выслушать деревенский сход в Зелёной лощине.'),
        t('The palace patrol counted our grain. Raut wants the same sacks for his mountain war. Neither asked who eats here. We will intercept the requisition caravan, not hire ourselves to it. First speak to Mara at Roadward: her last three drivers vanished beside our orchard. A raid on empty reins teaches us nothing.',
          'Дворцовый дозор пересчитал наше зерно. Раут требует те же мешки для своей горной войны. Ни один не спросил, что будем есть мы. Перехватим обоз с реквизицией, а не наймёмся его охранять. Сперва поговори с Марой на Трактовом дворе: трое её возчиков пропали у нашего сада. Нападение на пустые облучки ничего не объяснит.'),
        [a('elf-council', t('I answer to the households. I will identify the load before we strike.', 'Я отвечаю перед дворами. До удара выясню, что везут.'),
          t('The council entrusted me with the forest resistance. Mara is a witness and independent carrier, not my employer. The requisition caravan is our military target.',
            'Сход доверил мне лесное сопротивление. Мара — свидетельница и независимая перевозчица, не моя нанимательница. Обоз с реквизицией — наша военная цель.'),
          t('Then bring back names, not a boast about burnt wagons. Some of those drivers have kin here.',
            'Тогда принеси имена, не похвальбу о сожжённых телегах. У здешних есть родня среди возчиков.'))]),
      talk('mara', t('Ask the neutral carrier about the missing drivers.', 'Расспросить независимую перевозчицу о пропавших возчиках.'),
        t('I know that forest badge. If your people took my men, say so. Three carts came back with the barley intact and black panels hidden underneath. Here are their pay-token numbers and scars. Toman heard the first man answer his dead wife at the orchard; his handbell brought back the horses, not the men.',
          'Лесной знак я узнаю. Если твои взяли моих людей, скажи. Вернулись три телеги, ячмень цел, под ним чёрные пластины. Вот номера расчётных жетонов и приметы шрамов. Томан слышал, как первый у сада ответил умершей жене. На его колокол вернулись лошади, люди — нет.'),
        [a('elf-driver-names', t('We did not take them. I will follow the tracks and give you the evidence.', 'Мы их не брали. Пойду по следам и принесу доказательства.'),
          t('Mara gave me identifying records. She has not joined the resistance or surrendered her wagons; she expects an account of three missing people.',
            'Мара дала опознавательные записи. Она не вступала в сопротивление и не отдавала ему повозки; ей нужен ответ о трёх пропавших людях.'),
          t('The glass stays wrapped. And a guard wearing a palace coat is not proof that every driver serves the palace.',
            'Стекло оставлю завёрнутым. И дворцовый мундир на охраннике ещё не делает каждого возчика слугой дворца.'))]),
      e('elf', 'names-stones'),
      talk('toman', t('Set the resistance’s irreversible campaign directive.', 'Выбрать необратимое направление похода сопротивления.'),
        t('No returning footprints. The Caller borrows the dead; an answer draws the living after it. Keep the salt unbroken and someone at the bell. The chapel tag gives us a trail. Choose our campaign: shelter means liberating and supplying the forest post; interdiction adds the palace road post. Both require intercepting the requisition shipment, bringing it to the forest and defeating Raut. We cannot change the commitment once the households deploy.',
          'Обратных следов нет. Оклик берёт голоса мёртвых; ответившие живые идут за ним. Нужны целая полоса соли и человек у колокола. Бирка часовни даёт след. Выбери поход: защита требует освободить и снабдить лесную заставу; перерезать снабжение — ещё и дворцовый дорожный пост. В обоих случаях нужно перехватить реквизиционный груз, доставить его в лес и победить Раута. Когда дворы выделят людей, обязательство уже не изменить.'),
        [
          a('elf-supply-villages', t('Shelter: free and supply the forest post; bring the intercepted shipment home.', 'Защита: освободить и снабдить лесную заставу; доставить перехваченный груз домой.'),
            t('The council chose shelter. We must liberate and supply the forest post, recover the intercepted shipment there and defeat Raut. We do not require a further palace-post occupation.',
              'Сход выбрал защиту. Нужно освободить и снабдить лесную заставу, вернуть туда перехваченный груз и победить Раута. Дополнительное занятие дворцового поста не требуется.'),
            t('A shorter front leaves more of us near home, but does not cut the palace road. Follow the chapel freight through Mirecross.',
              'Короткий фронт оставит больше наших у дома, но дворцовую дорогу не перекроет. Следи за грузами часовни через Болотный брод.'), { directive: 'shelter', reputation: { commons: 3, registry: -1 } }),
          a('elf-supply-partisans', t('Interdict: hold and supply both forest and palace road posts.', 'Перерезать снабжение: взять и снабдить лесную заставу и дворцовый дорожный пост.'),
            t('The council chose interdiction. In addition to recovering the shipment to the forest and defeating Raut, we must capture and supply both the forest and palace road posts.',
              'Сход решил перерезать снабжение. Помимо возвращения груза в лес и победы над Раутом, нужно взять и снабдить и лесную заставу, и дворцовый дорожный пост.'),
            t('Then the war takes us farther from our doors. We chose it ourselves. Take that chapel tag to Sella at Mirecross.',
              'Тогда война уведёт нас дальше от своих дверей. Это наш выбор. Отнеси бирку часовни Селле в Болотный брод.'), { directive: 'interdict', reputation: { commons: -1, lanterns: 1 } }),
        ]),
    ]),
  chapter('elf-grave-freight', 'elf-wooden-walls', t('II. Graves on the Freight List', 'II. Могилы в грузовой описи'),
    t('Follow the intercepted evidence through the Fens and Salt Coast. People outside the forest do not owe the partisans their dead or their testimony.',
      'Проследить путь улик через Топи и Соляной берег. Люди за пределами леса не обязаны отдавать партизанам ни своих мёртвых, ни показания.'),
    t('The chapel freight remains an accusation without a buyer. The forest cannot make its own suffering proof of everyone else’s guilt.',
      'Груз часовни остаётся обвинением без установленного покупателя. Страдания леса сами по себе не доказывают чужой вины.'),
    [
      talk('sella', t('Trace the chapel tag with Sella.', 'Проследить бирку часовни с Селлой.'),
        t('I salvage for whoever pays, not for your uprising. But those crates were pulled from the Drowned Archive, and one broke on the steps. Look inside. You may find more than an excuse to stop a palace wagon.',
          'Я поднимаю грузы за плату, не ради вашего восстания. Но ящики эти из Затопленного архива; один разбился на ступенях. Загляни. Может, найдёшь нечто большее, чем повод остановить дворцовую телегу.'),
        [a('elf-river-witness', t('I want evidence, not your oath.', 'Мне нужны улики, не твоя присяга.'),
          t('Sella identified the recovered crates without taking a side in our war.', 'Селла опознала поднятые ящики, не принимая сторону в нашей войне.'),
          t('Third step is rotten. Independence will not hold it up under you.', 'Третья ступень сгнила. Независимость под тобой её не удержит.'))]),
      e('elf', 'river-plates'),
      talk('ivet', t('Ask Ivet what Raut’s men took.', 'Спросить Ивету, что забрали люди Раута.'),
        t('They called it emergency ward-making. Burial salt first, then things already in graves. My clothes resemble a guard’s; my patients do not thereby belong to the palace. I have one consignment left. We can refuse it openly, or mark it so Orsa can find the buyer. The second means letting stolen burial stores leave once more.',
          'Назвали срочным изготовлением защиты. Сперва погребальная соль, потом вещи из могил. Одежда у меня похожа на гвардейскую; больные от этого не стали дворцовой собственностью. Осталась одна партия. Можно открыто отказать. Можно пометить, чтобы Орса нашла покупателя. Но тогда украденные погребальные запасы снова уедут.'),
        [
          a('elf-chapel-refusal', t('Keep it. Our resistance will not demand your last salt.', 'Оставь груз. Сопротивление не потребует твою последнюю соль.'),
            t('Ivet refused the shipment. I supported a neutral chapel’s refusal, not an elven claim over its stores.',
              'Ивета отказалась от отправки. Я поддержал отказ независимой часовни, а не право эльфов на её запасы.'),
            t('Then the threshold gets salt tonight. Orsa can work from my tally.', 'Тогда сегодня на пороге будет соль. Орса сверит мою опись.'), { reputation: { lanterns: 2, commons: 1 } }),
          a('elf-chapel-trace', t('Mark one last load, with your consent. We need the buyer, not a scapegoat.', 'С твоего согласия пометим последний груз. Нам нужен покупатель, не крайний.'),
            t('Ivet consented to one marked consignment. We gained a trail at the expense of her remaining linen; this was not costless solidarity.',
              'Ивета согласилась на одну помеченную партию. Мы получили след ценой остатков её полотна; солидарность не обошлась без потерь.'),
            t('Crosses under the handles. I have kept salt for the door; do not let your people call the rest a gift.',
              'Кресты под ручками. Соль для двери оставила. Пусть твои не называют остальное подарком.'), { reputation: { commons: -1, lanterns: -1, registry: 1 } }),
        ]),
      talk('orsa', t('Check the cargo weights with Orsa.', 'Сверить вес грузов с Орсой.'),
        t('A forest blockade will not tell me who paid. The Tide Observatory kept the damaged barley freight and its weighing sling. Compare them before you stop my other loads. Neutral customers eat those.',
          'Лесная засада не скажет мне, кто платил. В Приливной башне остались повреждённый груз ячменя и весовая стропа. Сверь, прежде чем тормозить остальные партии. Их едят независимые заказчики.'),
        [a('elf-coast-weights', t('Only the requisition column is our target. I will check the sling.', 'Наша цель — обоз с реквизицией. Проверю стропу.'),
          t('I distinguished Raut’s requisition freight from Orsa’s independent trade and went to examine the unloading evidence.',
            'Я отделил реквизиционные грузы Раута от независимой торговли Орсы и отправился осматривать следы разгрузки.'),
          t('Keep the packing. A slogan is light; hidden glass is not.', 'Упаковку сохрани. Лозунг мало весит. Спрятанное стекло — немало.'))]),
      e('elf', 'winter-tides'),
    ]),
  chapter('elf-axes-and-orders', 'elf-grave-freight', t('III. Axes and Orders', 'III. Топоры и приказы'),
    t('The glass leads to Cinderwell and Crownbridge. Discover how Raut profits from stripped village wards, and confront the palace’s own part in the requisitions.',
      'Стекло ведёт в Углеземье и к Коронному мосту. Узнать, как Раут наживается на снятой деревенской защите, и предъявить дворцу его долю ответственности за поборы.'),
    t('The forest has an enemy’s name but not yet the chain of deliberate orders.', 'Лес знает имя врага, но ещё не доказал цепь сознательных приказов.'),
    [
      talk('beran', t('Question Beran about the wagon glass.', 'Расспросить Берана о стекле повозок.'),
        t('Yes, my stamp. Burial ash, salt, bell bronze. Some voices in the panes are prisoners holding the Caller out, not the Caller itself. Raut ordered a test at the Glass Quarry. Before you smash every pane, see what happened to the men in the bare frame.',
          'Да, моё клеймо. Погребальный пепел, соль, колокольная бронза. Некоторые голоса в пластинах — пленники, сдерживающие Оклик, а не сам Оклик. Раут заказал испытание в Стеклянном карьере. Прежде чем бить все пластины, посмотри, что случилось с людьми в открытом каркасе.'),
        [a('elf-foundry', t('Show me the test, including your own part in it.', 'Покажи испытание, в том числе своё участие.'),
          t('Beran admitted making the glass. Its victims may be holding back another danger; destroying it blindly would endanger the road.',
            'Беран признался в изготовлении стекла. Его жертвы, возможно, сдерживают другую угрозу; слепое разрушение подвергнет тракт опасности.'),
          t('The rejects are beside the cold furnace. My name is on them too.', 'Брак у холодной печи. На нём тоже моё имя.'))]),
      e('elf', 'winter-glass'),
      talk('vesk', t('Demand access to the requisition evidence at Crownbridge.', 'Потребовать доступ к уликам о реквизициях у Коронного моста.'),
        t('You come under a truce, not as my soldier. I signed palace allocations that left your granaries bare. Raut used his freight office to take burial stores as well. I kept the returned fittings and complaints in the Sealed Vault. You can inspect them; no oath to the palace is the price.',
          'Ты пришёл по перемирию, не как мой солдат. Я подписывал дворцовые наряды, опустошавшие ваши амбары. Раут через свою обозную службу забирал ещё и погребальные запасы. Возвращённые детали и жалобы я сохранил в Опечатанном подвале. Можешь осмотреть. Присяги дворцу взамен не требую.'),
        [a('elf-vault-access', t('I accept access, not your authority over Greenhollow.', 'Принимаю доступ, не твою власть над Зелёной лощиной.'),
          t('Vesk opened the evidence under a limited truce. His cooperation does not erase palace requisitions or bind the forest to his command.',
            'Веск открыл улики по ограниченному перемирию. Содействие не отменяет дворцовых реквизиций и не подчиняет лес его командованию.'),
          t('Understood. Take copies as well as parts; I will not be the only person keeping them.', 'Понятно. Возьми и копии, и детали. Пусть не только у меня хранятся.'))]),
      e('elf', 'weight-order'),
      talk('toman', t('Choose how the resistance uses the orders.', 'Решить, как сопротивление использует приказы.'),
        t('Raut knew. And Vesk cannot hide our empty barns behind Raut’s worse crimes. We can put both signatures before an open village hearing, or keep Vesk’s help quiet until the supply road is ours. An ally inside a storehouse is useful. So is a village that believes its own council.',
          'Раут знал. А Веск не спрячет наши пустые амбары за худшими преступлениями Раута. Можно вынести обе подписи на открытый деревенский разбор. Можно скрыть помощь Веска, пока не отобьём дорогу снабжения. Союзник внутри склада полезен. Как и деревня, которая верит своему сходу.'),
        [
          a('elf-open-hearing', t('Publish both signatures. A truce is not a pardon.', 'Огласим обе подписи. Перемирие не равно прощению.'),
            t('The council published the requisition evidence, including Vesk’s role. We refused to make our village witnesses subordinate to a useful palace contact.',
              'Сход огласил реквизиционные улики, включая роль Веска. Мы не подчинили деревенских свидетелей интересам полезного дворцового связного.'),
            t('Then our own claims can be questioned in public too. Nika at High Pass carried the warning Raut refused.',
              'Тогда и наши слова будут проверять при всех. Ника с Высокого перевала несла предупреждение, которое Раут отверг.'), { reputation: { commons: 2, registry: -2 } }),
          a('elf-hidden-copyist', t('Keep his channel open until the road is secured. Preserve copies outside the palace.', 'Сохраним его помощь до закрепления дороги. Копии оставим вне дворца.'),
            t('I concealed Vesk’s cooperation while keeping independent copies. The villages must wait to question him; the resistance now owes them an explanation.',
              'Я скрыл содействие Веска, сохранив независимые копии. Деревни пока не смогут его расспросить; сопротивлению придётся перед ними объясняться.'),
            t('Secrecy expires; do not let it become a habit of rule. Find Nika at High Pass.',
              'У тайны есть срок. Не делай её способом правления. Найди Нику на Высоком перевале.'), { reputation: { registry: 2, commons: -1 } }),
        ]),
    ]),
  chapter('elf-no-new-master', 'elf-axes-and-orders', t('IV. No New Master', 'IV. Без нового хозяина'),
    t('Cross Frostspine to learn how the road can be defended without another lord owning its shelter. Victory must secure the forest against both palace requisition and Raut’s mountain army.',
      'Перейти Инейный хребет и узнать, как защитить тракт, не отдав укрытие очередному властителю. Победа должна оградить лес и от дворцовых поборов, и от горного войска Раута.'),
    t('A defeated patrol is not independence. The posts and the ward still need people willing and able to maintain them.',
      'Разбитый дозор ещё не означает независимости. Заставам и защите всё ещё нужны люди, готовые и способные их содержать.'),
    [
      talk('nika', t('Hear Nika’s account on High Pass.', 'Выслушать Нику на Высоком перевале.'),
        t('Raut read the warning in front of me and asked how many wagons his glass could cover. On the way back the courier answered her dead brother below the path. I held her coat until she stopped climbing down. Your anger will not make that voice less persuasive. Lev kept the warning and the old fittings at Star Monastery.',
          'Раут при мне прочёл предупреждение и спросил, сколько возов укроет его стекло. На обратном пути гонец ответила покойному брату под тропой. Я держала её за полы, пока она не перестала лезть вниз. От твоей злости голос не станет менее убедительным. Лев сохранил предупреждение и старые детали в Звёздном монастыре.'),
        [a('elf-pass-warning', t('The dead are not our scouts. I will compare the fittings.', 'Мёртвые не наши разведчики. Сверю детали.'),
          t('Nika witnessed Raut’s refusal and saved a living listener from the Caller. An answer compels pursuit; it is not proof of instant death.',
            'Ника видела отказ Раута и спасла живую слушательницу от Оклика. Ответ тянет за голосом, но не доказывает мгновенной смерти.'),
          t('Then use the marked path. A partisan can fall off a cliff as readily as a soldier.', 'Тогда иди по вехам. Партизан падает со скалы не хуже солдата.'))]),
      e('elf', 'weight-census'),
      talk('toman', t('Set the forest’s terms for the last campaign.', 'Определить условия леса для последнего похода.'),
        t('Three bell watches could free the road from one binding, but Radek needs to cast three bells and Yara needs willing households with food for their dependents. Otherwise Elin may volunteer, or the glass goes and the long road loses shelter. None of this ends the war. Fulfil the directive: supply the forest post, also the palace road post if we chose interdiction, bring the intercepted shipment to the forest and defeat Raut. We fight so the villages can refuse the next demand.',
          'Три дозора могут освободить тракт от единой привязи, но Радек должен отлить три колокола, а Яра — найти добровольцев и еду их близким. Иначе Элин предложит себя или стекло разобьют, оставив дальний тракт без укрытия. Само это войну не закончило. Выполни решение: снабди лесную заставу, а при перерезании снабжения ещё и дворцовый пост, верни перехваченный груз в лес и победи Раута. Мы воюем, чтобы деревни могли отказать следующему сборщику.'),
        [a('elf-war-aim', t('No forest crown for me. Secure the road, then let the households judge its future.', 'Лесной короны мне не нужно. Отобьём дорогу, а её будущее решат дворы.'),
          t('The resistance reaffirmed its chosen military directive, including recovery of the intercepted shipment and Raut’s defeat, not inheritance of his right to demand obedience. Hollow Village holds the remaining evidence.',
            'Сопротивление подтвердило выбранное направление похода, включая возвращение перехваченного груза и победу над Раутом, а не наследование права требовать повиновения. Остальные улики в Глухой деревне.'),
          t('Ada keeps the graves there. Arrive as someone who can listen, not as another liberator counting what is owed.',
            'Могилы там хранит Ада. Приди как человек, способный слушать, не как очередной освободитель, считающий чужие долги.'))]),
    ]),
  chapter('elf-common-road', 'elf-no-new-master', t('V. A Road the Forest Can Refuse', 'V. Тракт без подневолья'),
    t('Identify Mara’s drivers in Hollowvale and examine the binding. Only after the forest’s military victory may the resistance enact a ward settlement.',
      'Опознать возчиков Мары в Глухой долине и осмотреть привязь. Только после военной победы леса сопротивление сможет исполнить решение о защите.'),
    t('The glass still holds captive voices. An unfulfilled promise of liberation leaves them exactly where Raut put them.',
      'Стекло всё ещё держит пленные голоса. Неисполненное обещание свободы оставляет их там, куда заточил Раут.'),
    [
      talk('ada', t('Ask Ada about the three graves.', 'Расспросить Аду о трёх могилах.'),
        t('Three dead drivers arrived with requisition freight from your orchard. I buried them. Their tokens and my notes are by the covered Echo Well. Being taken from elven land did not make them soldiers for either side. Stay inside Elin’s salt marks.',
          'С реквизиционным грузом из вашего сада привезли троих мёртвых возчиков. Я их похоронила. Жетоны и записи у закрытого Колодца эха. То, что их увели с эльфийской земли, не делает их бойцами какой-либо стороны. Держись соляных отметок Элина.'),
        [a('elf-hollow-witness', t('I will compare the names, not claim the dead for our cause.', 'Сверю имена, не стану записывать мёртвых в наше дело.'),
          t('Ada buried three drivers. Her notes can establish their identity, not a convenient story about who killed them.',
            'Ада похоронила троих возчиков. Её записи могут установить личности, а не удобную историю о том, кто их убил.'),
          t('Good. The voices under the lid are not survivors waiting to be recruited.', 'Хорошо. Голоса под крышкой — не выжившие, которых можно завербовать.'))]),
      e('elf', 'road-names'),
      e('elf', 'road-index'),
      talk('mara', t('Return the identification to Mara.', 'Вернуть Маре опознавательные записи.'),
        t('The numbers and the scars agree. All three. I will send the purses home, and I will name them as drivers, not martyrs of a war they never chose. You kept this promise. I have not thereby promised you my next cargo.',
          'Номера и шрамы совпадают. Все трое. Отправлю кошели домой. Назову их возчиками, не мучениками войны, которую они не выбирали. Это обещание ты сдержал. Я за это не обещала тебе следующий груз.'),
        [a('elf-wages-home', t('Their families owe the resistance nothing. Keep the originals.', 'Их семьи ничего не должны сопротивлению. Подлинники оставь себе.'),
          t('Mara confirmed the three deaths and took the records for their families. The precise cause remains unknown; neither the Caller’s voice nor our war supplies missing proof.',
            'Мара подтвердила гибель троих и взяла записи для семей. Точная причина неизвестна; ни голос Оклика, ни наша война не заменяют недостающих доказательств.'),
          t('Then go back to Elin. Keep the living off the unwarded stretches while you change anything.',
            'Тогда возвращайся к Элину. Пока меняете защиту, не пускайте живых на незащищённые перегоны.'))]),
      talk('elin', t('After victory, decide who keeps the forest road.', 'После победы решить, кто держит лесной тракт.'),
        t('Your military victory must be real before anyone opens this catch. Three bells need Radek’s three castings and Yara’s fed, willing watches. I can instead take the binding freely and never leave this cloister. Or we release the dead without a replacement and lose the glass shelter. Freedom is not a spell that keeps a cart safe at night.',
          'До размыкания нужна настоящая военная победа. Трём колоколам нужны три отливки Радека и сытые добровольные дозоры Яры. Или я добровольно приму привязь и больше не выйду из скита. Или отпустим мёртвых без замены и лишимся стеклянного укрытия. Свобода не заклинание, которое ночью оберегает телегу.'),
        [
          a('elf-ending-commons', t('Give the watches to the villages, never to a forest throne.', 'Передадим дозоры деревням, не лесному престолу.'),
            t('After securing the military route, we chose independent village watches. Three maintained bells replace the anchor before Elin releases the dead.',
              'Закрепив военный путь, мы выбрали независимые деревенские дозоры. Три обслуживаемых колокола заменяют привязь до освобождения мёртвых Элином.'),
            t('All three bells must answer before I open it. The villages keep their own ropes, and the right to stop traffic when a watch fails.',
              'Разомкну лишь после ответа всех трёх колоколов. У деревень свои верёвки и право остановить движение, если дозор не вышел.'),
            { ending: 'commons', gate: 'conquest', requiresActions: ['elf-bell-mourn', 'elf-stag-dependents'], reputation: { commons: 3, lanterns: 2 } }),
          a('elf-ending-compact', t('Accept Elin’s voluntary binding, with no council holding his only key.', 'Примем добровольную привязь Элина. Единственный ключ сходу не отдадим.'),
            t('After victory we accepted Elin’s informed offer. The forest gains shelter through one person’s confinement, not through a freedom it can honestly call universal.',
              'После победы мы приняли осознанное предложение Элина. Лес получает укрытие ценой заточения одного человека, а не свободу, которую можно честно назвать всеобщей.'),
            t('I consent to the fastening, not to your ownership. Let villagers and Candlekeepers both bring food and visitors.',
              'Я согласен на крепление, не на твоё владение мной. Пусть еду и посетителей приводят и деревенские, и Свечники.'),
            { ending: 'compact', gate: 'conquest', reputation: { lanterns: 1, commons: -1, registry: 1 } }),
          a('elf-ending-cinder', t('Release every captive. We accept the exposed road instead of another keeper.', 'Освободим всех пленников. Примем открытый опасностям тракт, а не нового смотрителя.'),
            t('After victory we chose to destroy the binding without replacement. The forest refuses another captive foundation and accepts less protected travel.',
              'После победы мы решили уничтожить привязь без замены. Лес отказывается строить защиту на новом пленнике и принимает менее безопасные поездки.'),
            t('Then clear the road first. Salt and tended bells still protect their own boundaries; the old glass will shelter no long crossing.',
              'Тогда сперва очистите тракт. Соль и колокола с дежурными по-прежнему защищают свои границы. Старое стекло больше не укроет дальний переход.'),
            { ending: 'cinder', gate: 'conquest', reputation: { lanterns: 3, registry: -2 } }),
        ]),
    ]),
];

export const ELF_ENDINGS: Record<EndingId, LocalizedText> = {
  commons: t('The Uncrowned Watches', 'Дозоры без короны'),
  compact: t('One Door Left Shut', 'Одна запертая дверь'),
  cinder: t('The Forest Takes the Night', 'Лес принимает ночь'),
};

export const ELF_EPILOGUES: Record<EndingId, LocalizedText> = {
  commons: t(
    'Raut is defeated, the intercepted shipment has reached the forest and the council’s chosen front is supplied. Radek’s three bells reach Yara’s willing watches. Only when every bell answers does Elin release the dead. Greenhollow keeps its wooden hall, not a new palace. The villages can refuse troops, but must also feed the households that keep watch. A harvest dispute closes one stretch for two days. Traders complain; the council will not compel a hungry family to ring. Mara pays the drivers’ families and bargains for passage as an independent carrier. The forest has won the right to answer for itself, not the right to stop answering others.',
    'Раут побеждён, перехваченный груз доставлен в лес, выбранный сходом фронт снабжён. Три колокола Радека доставлены добровольным дозорам Яры. Элин отпускает мёртвых только после ответа каждого колокола. В Зелёной лощине остаётся деревянный дом схода, а не новый дворец. Деревни вправе отказать войскам, но обязаны кормить семьи дозорных. Из-за спора о жатве один участок закрывается на два дня. Торговцы жалуются; сход не гонит голодную семью к верёвке. Мара выплачивает деньги семьям возчиков и договаривается о проезде как независимая перевозчица. Лес завоевал право отвечать за себя, а не право перестать отвечать перед другими.'),
  compact: t(
    'The forest wins its military campaign, but its victory has one boundary that cannot be opened. Elin willingly closes the wrist-piece and releases the captive dead; he can walk only as far as the cloister gate. The road keeps its shelter. Toman refuses a proposal to put a partisan sentry in sole charge of Elin’s visitors. Candlekeepers hold a second key and independent stores, yet every winter someone must cross hostile ground to replenish them. Mara sends the drivers’ wages home. Children in Greenhollow grow up hearing that no ruler owns them. When they ask why Elin cannot come to the harvest feast, the adults must tell the whole story.',
    'Лес выигрывает военный поход, но у победы есть одна граница, которую нельзя открыть. Элин добровольно замыкает обруч и освобождает пленных мёртвых; сам он может дойти лишь до ворот скита. Тракт сохраняет укрытие. Томан отвергает предложение поставить партизанского часового единолично решать, кого пускать к Элину. У Свечников второй ключ и отдельные припасы, но каждую зиму кому-то придётся пополнять их через опасные земли. Мара отправляет жалованье возчиков домой. Дети Зелёной лощины растут со словами, что ни один властитель ими не владеет. Когда они спрашивают, почему Элин не приходит на праздник урожая, взрослым приходится рассказывать всё.'),
  cinder: t(
    'With the forest post supplied and the resistance’s chosen campaign won, the crews break the anchor after clearing the road. The dead leave; no living prisoner replaces them. Raut’s glass no longer buys passage. Neither does a forest badge keep the Caller out between tended boundaries. Partisans guide daylight convoys and return to their farms exhausted. Two exposed hamlets move inside Greenhollow before winter; the orchard loses land to new houses. Mara pays the three families and writes risk payments into her next contract. The forest has refused to live on captive voices. It will not get back everything that refusal costs.',
    'Лесная застава снабжена, выбранный сопротивлением поход выигран; рабочие освобождают тракт и разбивают привязь. Мёртвые уходят; живого пленника вместо них нет. Стекло Раута больше не покупает проход. Но и лесной знак не отгоняет Оклик между оберегаемыми границами. Партизаны ведут обозы засветло и возвращаются на поля измотанными. До зимы два открытых опасности хутора переселяются в Зелёную лощину; часть сада уходит под дома. Мара платит трём семьям и включает надбавку за риск в следующий договор. Лес отказался жить за счёт пленных голосов. Не всё, чем обошёлся этот отказ, удастся вернуть.'),
};

export const ELF_NPCS = residents('elf', {
  mara: {
    greeting: t('Forest colors. Leave your quarrel outside my yard; the missing men are not prizes.', 'Лесные цвета. Оставь войну за двором: пропавшие люди не трофеи.'),
    localQuestion: t('Will you carry supplies for the resistance?', 'Повезёшь припасы сопротивлению?'),
    local: t('By agreement, with the drivers told what they carry. Roadward is a neutral human inn, not a partisan depot. Your own convoy must supply the posts you take.',
      'По договору, если возчики знают, что везут. Трактовый двор — независимый людской постоялый двор, не партизанский склад. Взятые заставы снабжает твой обоз.'),
    reactions: [{ after: 'elf-road-names', text: t('Ada’s records name all three. We will speak of them as people, not evidence that your entire side is right.', 'В записях Ады все трое. Будем говорить о людях, не о доказательстве безусловной правоты вашей стороны.') }],
  },
  toman: {
    role: t('Miller and resistance councillor', 'Мельник и член схода сопротивления'),
    greeting: t('You are home. The council left you a place, not a throne. Sit while I finish this bell rope.', 'Ты дома. Сход оставил тебе место, не трон. Садись, пока закончу колокольную верёвку.'),
    reactions: [
      { after: 'elf-supply-villages', text: t('Shelter, not a march for every post. Supply the forest and recover the shipment there before facing Raut.', 'Защита, не поход за всеми заставами. Снабди лес и верни туда груз, прежде чем идти на Раута.') },
      { after: 'elf-supply-partisans', text: t('We chose to cut the road. Both forest and palace posts must be taken and supplied; the shipment belongs back in the forest.', 'Мы решили перерезать дорогу. Лесной и дворцовый посты нужно взять и снабдить; груз должен вернуться в лес.') },
    ],
  },
  lida: { greeting: t('You can carry a partisan bow and still hold this graft steady. Help, then talk.', 'Партизанский лук не мешает подержать прививку. Помоги, потом поговорим.') },
  yara: { greeting: t('We defend these woods. That does not make every frightened household ours to order about.', 'Мы защищаем этот лес. Это не даёт нам права командовать каждой испуганной семьёй.') },
  sella: { greeting: t('Your forest council does not set my salvage rates. Evidence I can discuss.', 'Лесной сход не назначает мои расценки. Об уликах поговорить можно.') },
  ivet: { greeting: t('Bows outside the sickroom. I treat palace conscripts and your wounded on the same clean sheets.', 'Луки оставь за палатой. Дворцовые новобранцы и ваши раненые лежат на одинаково чистых простынях.') },
  oss: { greeting: t('No ambush on my ferry. Whoever is on the plank gets to the other bank first.', 'На моём пароме засад нет. Кто уже на доске, сперва попадёт на другой берег.') },
  orsa: { greeting: t('Which load do you dispute? Not every wagon beyond the forest belongs to your enemy.', 'Какой груз оспариваешь? Не каждая телега за лесом принадлежит твоему врагу.') },
  dren: { greeting: t('We pulled survivors out, not allies. Your banner will not sort the wet blankets.', 'Мы вытаскивали выживших, не союзников. Твоё знамя мокрые одеяла не разберёт.') },
  hana: { greeting: t('Do not hang a resistance flag on my signal bracket. Ships need the bearing clear.', 'Не вешай знамя сопротивления на крепление сигнала. Судам нужен ясный створ.') },
  beran: { greeting: t('You came to question my glass. Stand behind the chalk, even if you hate the answer.', 'Ты пришёл спросить о стекле. За мелом стой, даже если ответ не понравится.') },
  tessa: { greeting: t('I need clean water, not a declaration that the forest is innocent. Hold these jars.', 'Мне нужна чистая вода, не заявление о невиновности леса. Подержи банки.') },
  vesk: {
    name: t('Commander Vesk', 'Командир Веск'), role: t('Crownbridge garrison commander', 'Командир гарнизона Коронного моста'),
    greeting: t('You have safe conduct to this desk. It is not a request for your allegiance.', 'До этого стола тебе дан безопасный проход. Присяги я не прошу.'),
    localQuestion: t('Why let a partisan see your records?', 'Зачем показывать партизану свои записи?'),
    local: t('Because Raut’s freight network crossed our offices. I cannot defend the palace by hiding what passed through it. The truce lets witnesses reach the vault; it does not settle who governs the forest.',
      'Потому что обозная сеть Раута проходила через наши конторы. Дворец не защитить сокрытием того, что через него прошло. По перемирию свидетели доберутся до подвала; власть над лесом оно не определяет.'),
    beliefQuestion: t('Does an order excuse taking our grain?', 'Приказ оправдывает изъятие нашего зерна?'),
    belief: t('It tells you who ordered it. Whether it can be defended is a different question, and I expect your witnesses to ask it.',
      'Он говорит, кто распорядился. Можно ли это оправдать — другой вопрос. Ожидаю его от ваших свидетелей.'),
  },
  radek: { greeting: t('Bronze has no loyalty to the forest or the palace. A cracked crown will drop either bell.', 'Бронза не верна ни лесу, ни дворцу. С треснувшей короной упадёт любой колокол.') },
  nika: { greeting: t('Another person from the low woods. Up here a familiar accent is not a safe path.', 'Ещё человек из нижних лесов. Здесь знакомый говор не заменит надёжной тропы.') },
  lev: { greeting: t('You may read the ward books without joining our order. Dry your hands first.', 'Книги о защите можно читать без вступления в наш орден. Сперва высуши руки.') },
  ada: { greeting: t('Your council is far away. Here you step around the salt like everyone else.', 'Ваш сход далеко. Здесь ты обходишь соль, как все остальные.') },
  mila: { greeting: t('Do you need this coat mended or its former owner judged? I can do the first.', 'Кафтан чинить или прежнего хозяина судить? Первое я умею.') },
  elin: {
    greeting: t('A broken chain can fall on someone. Look at the fastening before promising to free the road.', 'Разорванная цепь может на кого-нибудь упасть. Осмотри крепление, прежде чем обещать свободу тракту.'),
    localQuestion: t('What must the resistance secure before the binding changes?', 'Что сопротивлению нужно закрепить до изменения привязи?'),
    local: t('Complete your chosen directive: supply the liberated forest post and, for interdiction, the palace road post too; recover the shipment to the forest and defeat Raut. Then bring workers and provisions. Three independent watches need Radek’s three bells and Yara’s willing keepers; one heavy bell is not a substitute.',
      'Выполни выбранное решение: снабди освобождённую лесную заставу, а для перерезания снабжения ещё и дворцовый пост; верни груз в лес и победи Раута. Потом нужны рабочие и припасы. Для трёх независимых дозоров необходимы три колокола Радека и добровольцы Яры; один тяжёлый их не заменит.'),
  },
  ren: {
    greeting: t('A partisan at my wheel bench. You may inspect the hub; you may not requisition Mara’s tools.', 'Партизан у моего верстака. Втулку осмотреть можно. Реквизировать инструменты Мары — нельзя.'),
  },
});
