import type { FactionId, LocalizedText } from './types';

export const text = (en: string, ru: string): LocalizedText => ({ en, ru });
export type CivicFaction = 'commons' | 'registry' | 'lanterns';
export type EndingId = 'commons' | 'compact' | 'cinder';
export interface StoryAction {
  id: string;
  text: LocalizedText;
  entry: LocalizedText;
  reputation?: Partial<Record<CivicFaction, number>>;
  ending?: EndingId;
  gate?: 'conquest';
}
export interface StoryStage {
  kind: 'talk' | 'inspect';
  at: string;
  objective: LocalizedText;
  prompt: LocalizedText;
  actions: StoryAction[];
}
export interface StoryQuest {
  id: string;
  kind: 'main' | 'side';
  title: LocalizedText;
  description: LocalizedText;
  requires: string | null;
  reward: number;
  stages: StoryStage[];
}
export interface StoryNpc {
  id: string;
  locationId: string;
  name: LocalizedText;
  role: LocalizedText;
  faction: FactionId;
  activity: LocalizedText;
  greeting: LocalizedText;
  local: LocalizedText;
  belief: LocalizedText;
}

const action = (id: string, en: string, ru: string, entryEn: string, entryRu: string,
  reputation?: StoryAction['reputation']): StoryAction => ({
  id, text: text(en, ru), entry: text(entryEn, entryRu), ...(reputation ? { reputation } : {}),
});
const talk = (at: string, en: string, ru: string, promptEn: string, promptRu: string,
  actions: StoryAction[]): StoryStage => ({
  kind: 'talk', at, objective: text(en, ru), prompt: text(promptEn, promptRu), actions,
});
const inspect = (at: string, id: string, en: string, ru: string, entryEn: string, entryRu: string): StoryStage => ({
  kind: 'inspect', at, objective: text(en, ru), prompt: text(entryEn, entryRu),
  actions: [action(id, 'Examine the evidence.', 'Изучить улику.', entryEn, entryRu)],
});

export const CIVIC_FACTIONS: { id: CivicFaction; name: LocalizedText }[] = [
  { id: 'commons', name: text('Road Commons', 'Дорожные общины') },
  { id: 'registry', name: text('Toll Registry', 'Палата сборов') },
  { id: 'lanterns', name: text('Lantern Network', 'Сеть фонарщиков') },
];

export const ENDINGS: Record<EndingId, LocalizedText> = {
  commons: text('The Road of Witnesses', 'Дорога свидетелей'),
  compact: text('The Winter Compact', 'Зимний договор'),
  cinder: text('The Road Without Ink', 'Дорога без чернил'),
};

export const QUESTS: StoryQuest[] = [
  {
    id: 'missing-names', kind: 'main', requires: null, reward: 30,
    title: text('I. The Village Below the Line', 'I. Деревня под чертой'),
    description: text(
      'Your conquest needs roads that feed people, not empty victories. Roadward receives a cart addressed to a village the toll books say never existed.',
      'Для завоевания нужны дороги, которые кормят людей, а не пустые победы. В Дорожный двор прибыла телега для деревни, которой якобы никогда не было.'),
    stages: [
      talk('mara', 'Ask Mara at Roadward about the unclaimed grain.', 'Расспросить Мару в Дорожном дворе о невостребованном зерне.',
        'The fortress commands the road; its clerks decide who is allowed to need it. Win your posts, captain, but first learn whose mouths have been crossed out.',
        'Крепость правит дорогой, а писцы решают, кому позволено в ней нуждаться. Бери заставы, капитан, но сперва узнай, чьи рты вычеркнули.',
        [action('names-start', 'Take the returned delivery slip to Greenhollow.', 'Отнести возвратную накладную в Зелёную ложбину.',
          'Mara gave me a delivery slip: Greenhollow, population zero. The driver heard children behind the shuttered mill.',
          'Мара дала накладную: Зелёная ложбина, население ноль. Возчик слышал детей за ставнями мельницы.')]),
      talk('toman', 'Find Toman in Greenhollow.', 'Найти Томана в Зелёной ложбине.',
        'I signed a smaller harvest so the collectors would leave seed for spring. Someone changed a smaller harvest into no village at all. The old orchard keeps our boundary stones.',
        'Я занизил урожай, чтобы сборщики оставили семена на весну. Кто-то превратил малый урожай в несуществующую деревню. В старом саду сохранились межевые камни.',
        [action('names-witness', 'Compare his account with the orchard stones.', 'Сверить его слова с камнями в саду.',
          'Toman admits falsifying the harvest, not the population. The orchard may prove the settlement predates the debt.',
          'Томан признаёт подлог урожая, но не населения. Сад может доказать, что деревня старше её долга.')]),
      inspect('old-orchard', 'names-stones', 'Inspect the carved boundary stones at the Old Orchard.',
        'Осмотреть резные межевые камни Старого сада.',
        'Under new toll paint are birth names and planting dates. A registry order erased the village after its debt was sold to the fortress.',
        'Под свежей краской сборщиков — имена новорождённых и даты посадок. Палата вычеркнула деревню после продажи её долга крепости.'),
      talk('toman', 'Decide how to protect Greenhollow with Toman.', 'Решить с Томаном, как защитить Зелёную ложбину.',
        'Use my confession and the names become evidence, but the collectors will know every witness. Hide me and the families survive this week; the fraud will be harder to prove.',
        'С моим признанием имена станут доказательством, но сборщики узнают всех свидетелей. Спрячешь меня — семьи переживут неделю, а подлог будет труднее доказать.',
        [
          action('names-public', 'Publish the names and his confession; protect the witnesses openly.',
            'Обнародовать имена и признание; открыто защищать свидетелей.',
            'Greenhollow returned to the public rolls. Toman will face an inquiry; the Commons can now demand grain in daylight.',
            'Зелёная ложбина вернулась в открытые списки. Томану грозит дознание, зато общины могут требовать зерно при свете дня.', { commons: 2, registry: 1, lanterns: -1 }),
          action('names-shelter', 'Hide the families through the Lantern Network; keep the confession private.',
            'Спрятать семьи через фонарщиков; сохранить признание в тайне.',
            'The families received secret shelter. Their names remain absent from public books; the Lanterns now carry the cost of feeding them.',
            'Семьи укрыты тайно. В открытых книгах их по-прежнему нет; теперь фонарщики должны их прокормить.', { commons: 1, registry: -1, lanterns: 2 }),
        ]),
    ],
  },
  {
    id: 'river-record', kind: 'main', requires: 'missing-names', reward: 35,
    title: text('II. What the River Kept', 'II. Что сохранила река'),
    description: text('Follow the erased debt west into Fenlands. Someone drowned an archive, but not all of its witnesses.',
      'Проследить стёртый долг до болот. Кто-то затопил архив, но утонули не все свидетели.'),
    stages: [
      talk('sella', 'Ask Sella at Mirecross about the drowned debt records.', 'Расспросить Селлу в Болотном броде о затопленных долговых книгах.',
        'The river rose after the archive sluice opened from inside. Read the brass plates below its stairs. Paper rots; a cheap bureaucracy uses brass twice.',
        'Вода поднялась после того, как шлюз архива открыли изнутри. Читай латунные пластины под лестницей. Бумага гниёт, а бережливая канцелярия использует латунь дважды.',
        [action('river-start', 'Investigate the Drowned Archive.', 'Расследовать гибель Затопленного архива.',
          'Sella points to reused brass plates. A deliberate flood destroyed the debt originals.',
          'Селла указала на старые латунные пластины. Подлинники долгов уничтожило намеренное затопление.')]),
      inspect('drowned-archive', 'river-plates', 'Inspect the brass plates at the Drowned Archive.', 'Осмотреть латунные пластины Затопленного архива.',
        'The reversed plates list grain diverted to military storehouses, then charged again to the vanished villages. A chapel seal authorized the copies.',
        'На обороте пластин — зерно, отведённое в военные склады и снова записанное в долг исчезнувшим деревням. Копии заверены печатью часовни.'),
      talk('ivet', 'Confront Ivet at Reed Chapel with the duplicate debts.', 'Предъявить Ивете в Камышовой часовне двойные долги.',
        'I copied the orders because the chapel received winter flour. Our sick lived on stolen grain. Publish my ledger and the next shipment stops. Seal it and the fraud survives.',
        'Я переписывала приказы, потому что часовня получала зимнюю муку. Наши больные жили на краденом зерне. Откроешь книгу — поставки прекратятся. Спрячешь — подлог уцелеет.',
        [
          action('river-open', 'Release the ledger and organize public relief instead.', 'Открыть книгу и организовать помощь общин.',
            'The double debts are public. The chapel lost its privileged flour; the Commons promised to share their own winter store.',
            'Двойные долги обнародованы. Часовня лишилась привилегий; общины обещали поделиться своими зимними запасами.', { commons: 2, registry: -2 }),
          action('river-seal', 'Keep a sealed copy for trial; preserve the chapel supply line.', 'Оставить запечатанную копию для суда; сохранить поставки часовне.',
            'I kept a sealed copy. The chapel still eats, but families paying twice must wait for justice.',
            'Копия запечатана. Часовня пока сыта, но семьям, платящим дважды, придётся ждать справедливости.', { registry: 2, lanterns: 1, commons: -1 }),
        ]),
    ],
  },
  {
    id: 'winter-price', kind: 'main', requires: 'river-record', reward: 40,
    title: text('III. The Price of Winter', 'III. Цена зимы'),
    description: text('Saltcoast grain contracts and Ashsteppe furnaces share the same invisible owners. Find out what the fortress really buys.',
      'У зерновых договоров Солёного берега и печей Пепельной степи одни невидимые хозяева. Узнать, что на самом деле покупает крепость.'),
    stages: [
      talk('orsa', 'Question Orsa at Saltmarket about fortress contracts.', 'Расспросить Орсу на Солёном рынке о договорах крепости.',
        'There is enough grain on paper to feed the border twice. Check the tide observatory: its weights record actual ships, not promises.',
        'На бумаге зерна хватит дважды прокормить пограничье. Проверь приливную обсерваторию: её весы считают настоящие суда, а не обещания.',
        [action('winter-start', 'Trace the ships at the Tide Observatory.', 'Проследить суда по записям Приливной обсерватории.',
          'Orsa suspects the fortress buys receipts without buying grain. The observatory recorded the real tonnage.',
          'Орса подозревает: крепость покупает расписки, а не зерно. Обсерватория записывала настоящий тоннаж.')]),
      inspect('tide-observatory', 'winter-tides', 'Inspect the Tide Observatory weight records.', 'Изучить весовые записи Приливной обсерватории.',
        'The grain ships arrived half empty. Their other cargo was furnace glass from Cinderwell, paid for with village food allotments.',
        'Зерновые суда приходили полупустыми. Остальной груз — печное стекло из Углеземья, оплаченное деревенскими пайками.'),
      talk('beran', 'Ask Beran in Cinderwell who ordered the furnace glass.', 'Узнать у Берана в Углеземье, кто заказал печное стекло.',
        'Glass seals cannot be scraped clean like wax. We made a permanent name for every debt. Go to the quarry furnace; the discarded molds still hold the names.',
        'Стеклянную печать не соскоблить, как воск. Мы дали каждому долгу вечное имя. В печи каменоломни остались формы с именами.',
        [action('winter-molds', 'Follow the order to Glass Quarry.', 'Проследить заказ до Стеклянной каменоломни.',
          'Beran forged unalterable debt seals, not weapons. The fortress means to make emergency hunger hereditary.',
          'Беран делал несмываемые долговые печати, а не оружие. Крепость хочет превратить голодный долг в наследственный.')]),
      inspect('glass-quarry', 'winter-glass', 'Inspect the discarded glass molds at Glass Quarry.', 'Осмотреть стеклянные формы Стеклянной каменоломни.',
        'Children not yet born are named as debtors. The mold order bears the crown treasury seal, and the Saltmarket ration contract can fund one countermeasure.',
        'Должниками названы ещё не рождённые дети. На заказе печатей — знак казны; договор Солёного рынка оплатит лишь одну ответную меру.'),
      talk('orsa', 'Choose a grain policy with Orsa at Saltmarket.', 'Выбрать с Орсой на Солёном рынке порядок выдачи зерна.',
        'Your captured posts can carry food, not just banners. We can ration it through audited books or open the stores without papers. Neither feeds everyone first.',
        'Твои заставы могут нести не только знамёна, но и пищу. Выдадим пайки по проверенным книгам или откроем склады без бумаг. Первыми получат еду не все.',
        [
          action('winter-ration', 'Audit the ration books; guarantee measured winter portions.',
            'Проверить списки; гарантировать размеренные зимние пайки.',
            'Audited rations protect the winter reserve. Unregistered refugees must find a sponsor before they can eat from it.',
            'Проверенные пайки защитят зимний запас. Беженцам без записи нужен поручитель, прежде чем они получат еду.', { registry: 2, commons: 1, lanterns: -1 }),
          action('winter-open', 'Open the granaries to everyone, including the unregistered.',
            'Открыть амбары для всех, включая незаписанных.',
            'The doors are open and hungry strangers eat today. No clerk can promise what will remain at winter end.',
            'Двери открыты, голодные чужаки едят сегодня. Ни один писец не обещает, что останется к концу зимы.', { commons: 2, lanterns: 2, registry: -2 }),
        ]),
    ],
  },
  {
    id: 'weight-of-names', kind: 'main', requires: 'winter-price', reward: 45,
    title: text('IV. The Weight of a Name', 'IV. Вес имени'),
    description: text('The Crownlands hold the lawful order; Frostspine holds the original census. A victory needs more than a guilty commander.',
      'В Коронных землях хранится законный приказ, в Ледяном хребте — подлинная перепись. Для победы мало виновного командира.'),
    stages: [
      talk('vesk', 'Ask Vesk at Crownbridge for access to the tax records.', 'Попросить Веска у Коронного моста показать податные записи.',
        'The commander used a lawful emergency decree. I signed it before I read the villages it would erase. The vault has my order. I will not call it a forgery.',
        'Командир воспользовался законным чрезвычайным указом. Я подписал его, не прочитав список исчезающих деревень. В хранилище мой приказ. Я не назову его подделкой.',
        [action('weight-start', 'Read the order in the Tax Vault.', 'Прочесть приказ в Податном хранилище.',
          'Vesk admits the legal seal is his. The wrongdoing began before the fortress commander took power.',
          'Веск признаёт свою законную печать. Преступление началось ещё до прихода командира крепости.')]),
      inspect('tax-vault', 'weight-order', 'Inspect the emergency decree at the Tax Vault.', 'Изучить чрезвычайный указ в Податном хранилище.',
        'The decree permits removing "unproductive settlements." A missing census appendix defines people as production. A monastery copy traveled through High Pass.',
        'Указ разрешает убирать «непроизводительные поселения». В пропавшем приложении люди приравнены к продукции. Монастырская копия прошла через Высокий перевал.'),
      talk('nika', 'Ask Nika at High Pass about the census courier.', 'Расспросить Нику на Высоком перевале о гонце с переписью.',
        'The courier paid with her last boots. I gave her mine. The monks kept her census, but would not put a shoeless stranger in their guest book.',
        'Гонец расплатилась последними сапогами. Я отдала ей свои. Монахи сберегли перепись, но босую чужачку в книгу гостей не внесли.',
        [action('weight-courier', 'Seek the original census at Star Monastery.', 'Найти подлинную перепись в Звёздном монастыре.',
          'Nika saw the courier alive. The census includes transient workers the tax authorities refuse to count.',
          'Ника видела гонца живой. В переписи есть сезонные работники, которых сборщики не желают считать.')]),
      inspect('star-monastery', 'weight-census', 'Inspect the original census at Star Monastery.', 'Изучить подлинную перепись Звёздного монастыря.',
        'The original counts every resident, including travelers. A margin points to Hollowvale: the first village erased, where the master index was moved.',
        'Подлинник считает каждого жителя, включая путников. На полях — ссылка на Пустодол: первую стёртую деревню, куда перенесли главный указатель.'),
      talk('vesk', 'Decide Vesk\'s responsibility at Crownbridge.', 'Решить судьбу Веска у Коронного моста.',
        'Put me on trial and the order becomes a crime. Keep me in office and I can revoke it tonight. The judges will ask why a conqueror gets to choose.',
        'Отдай меня под суд — приказ станет преступлением. Оставь у власти — я отменю его сегодня. Судьи спросят, почему выбирать позволено завоевателю.',
        [
          action('weight-trial', 'Hold a public trial, including your own military requisitions.',
            'Провести открытый суд, включая собственные военные реквизиции.',
            'Vesk will stand trial beside the orders I issued. The Commons gain oversight, but the registry loses its only willing administrator.',
            'Веск предстанет перед судом вместе с моими приказами. Общины получат надзор, но палата потеряет единственного готового помочь управителя.', { commons: 2, registry: -2 }),
          action('weight-pardon', 'Offer a conditional pardon in exchange for immediate repeal.',
            'Дать условное прощение за немедленную отмену указа.',
            'Vesk revoked the decree under my protection. The clerks can work tomorrow; those buried without names receive no trial.',
            'Под моей защитой Веск отменил указ. Писцы завтра продолжат работу; похороненные без имён суда не получат.', { registry: 3, commons: -1, lanterns: -1 }),
        ]),
    ],
  },
  {
    id: 'unwritten-road', kind: 'main', requires: 'weight-of-names', reward: 50,
    title: text('V. The Unwritten Road', 'V. Ненаписанная дорога'),
    description: text('Find the master index in Hollowvale. Decide who may write the next road, then secure the fortress so that decision can endure.',
      'Найти главный указатель в Пустодоле. Решить, кому писать новую дорогу, и взять крепость, чтобы решение выстояло.'),
    stages: [
      talk('ada', 'Speak to Ada in Hollow Village about its missing name.', 'Поговорить с Адой в Пустой деревне о пропавшем имени.',
        'They did not burn our homes. They stopped every cart until people left them. The Name Well holds what we refused to surrender. Listen before you write us a better cage.',
        'Они не жгли наши дома. Они останавливали телеги, пока люди не ушли. В Колодце имён осталось то, что мы не отдали. Послушай, прежде чем писать нам лучшую клетку.',
        [action('road-start', 'Read the names preserved at the well.', 'Прочесть сохранённые у колодца имена.',
          'Ada stayed to bury those who could not leave. The erasure was a siege conducted without soldiers.',
          'Ада осталась хоронить тех, кто не смог уйти. Стирание оказалось осадой без солдат.')]),
      inspect('name-well', 'road-names', 'Inspect the offerings inside the Name Well.', 'Осмотреть подношения в Колодце имён.',
        'Each bowl carries a name, not a debt. One belongs to the census courier, who reached the Last Archive and never returned.',
        'На каждой миске имя, а не долг. Одна принадлежит гонцу с переписью: она дошла до Последнего архива и не вернулась.'),
      inspect('last-archive', 'road-index', 'Inspect the master index at the Last Archive.', 'Изучить главный указатель Последнего архива.',
        'The master index links every erased name to a living creditor. The courier sealed herself inside to prevent its destruction. Her final note asks for witnesses, not revenge.',
        'Главный указатель связывает каждое стёртое имя с живым кредитором. Гонец заперлась внутри, спасая его. В последней записке она просит свидетелей, а не мести.'),
      talk('elin', 'Choose the road\'s future with Elin at the Last Archive when you are ready.',
        'Когда будете готовы, выбрать с Элином в Последнем архиве будущее дороги.',
        'Your posts and convoy make a promise enforceable. We can give the index to elected witnesses, bind the registry to a winter compact, or destroy the machinery of inherited debt. You may leave and finish other work before deciding.',
        'Твои заставы и обоз дадут обещанию силу. Указатель можно отдать выборным свидетелям, связать палату зимним договором или уничтожить сам механизм наследственного долга. Можно уйти и закончить другие дела до решения.',
        [
          { ...action('ending-commons', 'Entrust the index to elected witnesses. Local councils share the road.',
            'Передать указатель выборным свидетелям. Дорогу разделят местные советы.',
            'The index is copied into open village books. Elected witnesses can dispute any erasure, including one ordered by their liberator.',
            'Указатель скопирован в открытые деревенские книги. Выборные свидетели смогут оспорить любое стирание — даже по приказу освободителя.', { commons: 3, registry: -1 }), ending: 'commons', gate: 'conquest' },
          { ...action('ending-compact', 'Bind the Registry to a public winter compact. Preserve centralized supply.',
            'Связать палату открытым зимним договором. Сохранить единое снабжение.',
            'The Registry survives under a public charter. Food receives priority over debt, but the same desks still decide which petitions to hear first.',
            'Палата сохранена по открытому уставу. Еда важнее долга, но за теми же столами всё ещё решают, чьи просьбы слушать первыми.', { registry: 3 }), ending: 'compact', gate: 'conquest' },
          { ...action('ending-cinder', 'Burn the debt index after returning the names. Let communities make new pacts.',
            'Вернуть имена и сжечь долговой указатель. Пусть общины заключат новые договоры.',
            'The names go home; the hereditary debt index becomes ash. The Lanterns carry food without papers, and no one can guarantee a fair winter route.',
            'Имена вернулись домой, наследственный долговой указатель стал пеплом. Фонарщики везут еду без бумаг; справедливость зимних путей никто не гарантирует.', { lanterns: 3, commons: 1, registry: -3 }), ending: 'cinder', gate: 'conquest' },
        ]),
    ],
  },
  {
    id: 'orchard-claim', kind: 'side', requires: null, reward: 25,
    title: text('The Orchard of Two Widows', 'Сад двух вдов'),
    description: text('Two households claim the same orchard: one planted it, the other bought its debt. Recover the living history beneath the boundary.',
      'На сад претендуют две семьи: одна его посадила, другая купила долг. Восстановить живую историю под межой.'),
    stages: [
      talk('lida', 'Hear Lida\'s orchard dispute in Greenhollow.', 'Выслушать Лиду о спорном саде в Зелёной ложбине.',
        'My wife planted the trees. The widow who holds the deed sold her own home to buy it. Tell me which grief counts as ownership.',
        'Деревья посадила моя жена. Вдова с купчей продала ради неё свой дом. Скажи, какое горе даёт право собственности.',
        [action('orchard-start', 'Look for the planting pact at the Old Orchard.', 'Найти договор о посадке в Старом саду.',
          'Lida asks for the old planting pact, not the removal of her rival. The roots may preserve the terms.',
          'Лида просит найти старый договор, а не прогнать соперницу. У корней могли сохраниться условия.')]),
      inspect('old-orchard', 'orchard-pact', 'Inspect the old planting pact at the orchard.', 'Изучить старый посадочный договор в саду.',
        'The pact gave caretakers use of the fruit but never permitted sale of the land. Later debt papers promised a sale anyway.',
        'Договор отдавал плоды тем, кто ухаживает за садом, но запрещал продажу земли. Поздние долговые бумаги всё же обещали продажу.'),
      talk('lida', 'Settle the competing orchard claims with Lida.', 'Разрешить спор о саде с Лидой.',
        'Restore the old pact and she loses her last savings. Honor the deed and I lose the trees. A shared harvest could keep us both here, if either can bear it.',
        'Верни старый договор — она лишится последних сбережений. Признай купчую — я потеряю деревья. Общий урожай удержит нас обеих, если мы это вынесем.',
        [
          action('orchard-share', 'Establish shared care and a divided harvest.', 'Установить совместный уход и раздел урожая.',
            'Both widows keep a place at the orchard. Neither calls the settlement justice; both will be here for the blossom.',
            'Обе вдовы остались в саду. Ни одна не считает решение справедливым; обе увидят цветение.', { commons: 2 }),
          action('orchard-deed', 'Honor the paid deed; require wages for the original caretaker.', 'Признать оплаченную купчую; обязать платить прежней садовнице.',
            'The purchased deed stands. Lida now earns wages beneath trees her family planted; a legal sale has become a personal dispossession.',
            'Купчая признана. Лида получает плату под деревьями своей семьи; законная продажа стала личной утратой.', { registry: 2, commons: -1 }),
        ]),
    ],
  },
  {
    id: 'stag-oath', kind: 'side', requires: null, reward: 25,
    title: text('A Bell for the Antlered', 'Колокол для рогатых'),
    description: text('Thornwatch blames poachers for a silent shrine. Its oath may conceal a ration line reserved for the dead.',
      'Терновый дозор винит браконьеров в молчании святилища. Клятва может скрывать пайки, отведённые мёртвым.'),
    stages: [
      talk('yara', 'Hear Yara at Thornwatch.', 'Выслушать Яру в Терновом дозоре.',
        'We ring the shrine bell for every lost hunter. Someone took it, and the patrol blames children gathering antlers. Find the bell before they find the children.',
        'По каждому погибшему охотнику звонит колокол. Его украли, и дозор винит детей, собиравших рога. Найди колокол раньше, чем дозор найдёт детей.',
        [action('stag-start', 'Examine the Stag Shrine.', 'Осмотреть Оленье святилище.',
          'Yara fears a punishment disguised as piety. The shrine bell vanished without a cart passing Thornwatch.',
          'Яра боится наказания под видом благочестия. Колокол исчез, хотя ни одна телега не прошла дозор.')]),
      inspect('stag-shrine', 'stag-bell', 'Inspect the empty bell frame at Stag Shrine.', 'Осмотреть пустую раму колокола Оленьего святилища.',
        'The bell was buried beside ration tokens bearing dead hunters\' names. Their families used the tokens to feed children after survivor payments stopped.',
        'Колокол зарыт рядом с пайковыми жетонами погибших охотников. Когда выплаты семьям прекратились, жетонами кормили детей.'),
      talk('yara', 'Decide what Thornwatch hears about the missing bell.', 'Решить, что Терновый дозор узнает о пропавшем колоколе.',
        'I buried it. A public roll of the dead would cancel their rations. Restore the bell and name the living dependents, or keep our theft quiet.',
        'Я его зарыла. Открытый список мёртвых отменил бы их пайки. Верни колокол и запиши живых иждивенцев — или сохрани нашу кражу в тайне.',
        [
          action('stag-dependents', 'Register the dependents openly and restore the bell.', 'Открыто записать иждивенцев и вернуть колокол.',
            'The bell names the dead while a new roll names their dependents. The Commons must defend that entitlement at every audit.',
            'Колокол зовёт мёртвых, новый список называет их иждивенцев. Общины должны отстаивать это право при каждой проверке.', { commons: 2, registry: 1 }),
          action('stag-secret', 'Leave the false ration names intact; tell the patrol the bell cracked.', 'Сохранить ложные пайковые имена; сказать дозору, что колокол треснул.',
            'The bell stays buried. The children eat on dead names, safe until a more diligent collector arrives.',
            'Колокол остался в земле. Дети едят по именам мёртвых — до появления более усердного сборщика.', { lanterns: 2, registry: -1 }),
        ]),
    ],
  },
  {
    id: 'ferry-debt', kind: 'side', requires: null, reward: 30,
    title: text('The Passenger Who Paid Twice', 'Пассажир, заплативший дважды'),
    description: text('A ferryman carried refugees under cargo papers. One passenger never reached the far bank.',
      'Паромщик перевозил беженцев по грузовым бумагам. Один пассажир не добрался до другого берега.'),
    stages: [
      talk('oss', 'Ask Oss at Lantern Ferry about the missing passenger.', 'Расспросить Осса на Фонарной переправе о пропавшем пассажире.',
        'I charged him a fare and the Registry charged him as cargo. He jumped to save his daughter the second toll. The chapel took her blanket.',
        'Я взял плату за проезд, а палата обложила его как груз. Он прыгнул, чтобы дочь не платила второй сбор. Часовня забрала её одеяло.',
        [action('ferry-start', 'Look for the passenger token at Reed Chapel.', 'Найти пассажирский жетон в Камышовой часовне.',
          'Oss wants the passenger\'s daughter found. The chapel keeps the belongings of those pulled from the reeds.',
          'Осс хочет найти дочь пассажира. В часовне хранят вещи тех, кого вытащили из камышей.')]),
      inspect('reed-chapel', 'ferry-token', 'Inspect the rescued belongings at Reed Chapel.', 'Осмотреть спасённые вещи в Камышовой часовне.',
        'The daughter is alive on a relief list. Her blanket conceals an officer\'s waiver proving Oss could have carried them free.',
        'Дочь жива, её имя в списке помощи. В одеяле спрятано освобождение от сбора: Осс мог перевезти их бесплатно.'),
      talk('oss', 'Confront Oss with the unused waiver.', 'Предъявить Оссу неиспользованное освобождение от сбора.',
        'I knew. My ferry debt was due that morning. Take my license and the next refugees face the soldiers\' bridge. Keep it and I work for a man whose death I bought.',
        'Я знал. В то утро истекал долг за паром. Отбери разрешение — следующих беженцев ждёт солдатский мост. Оставь — я буду работать для человека, чью смерть купил.',
        [
          action('ferry-repay', 'Keep the ferry open; bind Oss to free refugee passage.', 'Сохранить переправу; обязать Осса бесплатно возить беженцев.',
            'Oss keeps the ferry under a witnessed restitution oath. The daughter will not forgive him; strangers will cross because of her father.',
            'Осс сохранил паром под засвидетельствованной клятвой возмещения. Дочь его не простит; чужие люди переправятся благодаря её отцу.', { lanterns: 2, commons: 1 }),
          action('ferry-trial', 'Revoke the license and send his confession to a public hearing.', 'Отозвать разрешение и направить признание на открытое слушание.',
            'Oss will answer publicly. The ferry awaits a replacement, and displaced families must risk the guarded bridge meanwhile.',
            'Осс ответит открыто. Паром ждёт нового перевозчика; пока беженцам придётся рисковать на охраняемом мосту.', { registry: 2, lanterns: -1 }),
        ]),
    ],
  },
  {
    id: 'wreck-light', kind: 'side', requires: null, reward: 30,
    title: text('A Light Facing Inland', 'Огонь, обращённый к суше'),
    description: text('A wreck fed Saltcoast for a month. The light that led it ashore was not an accident.',
      'Кораблекрушение кормило Солёный берег месяц. Огонь, приведший судно на мель, горел не случайно.'),
    stages: [
      talk('dren', 'Hear Dren at Wreckers\' Rest.', 'Выслушать Дрена в Приюте корабельщиков.',
        'They call us wreckers. We pulled twelve sailors out before we took a sack. Ask the observatory why its sea lantern pointed inland.',
        'Нас зовут губителями судов. Мы вытащили двенадцать моряков прежде, чем взяли мешок. Спроси обсерваторию, почему морской фонарь светил на сушу.',
        [action('wreck-start', 'Examine the Tide Observatory lantern mount.', 'Осмотреть крепление фонаря Приливной обсерватории.',
          'Dren claims the warning light was reversed before the storm. The salvage paid for an entire village\'s food.',
          'Дрен утверждает, что фонарь развернули до бури. Поднятого груза хватило прокормить всю деревню.')]),
      inspect('tide-observatory', 'wreck-mount', 'Inspect the reversed lantern mount.', 'Осмотреть повёрнутое крепление фонаря.',
        'Fresh tool marks prove the lantern was reversed. The repair order bears Dren\'s mark, beside a rejected plea for emergency food.',
        'Свежие следы инструмента доказывают разворот фонаря. На наряде знак Дрена; рядом — отклонённая просьба о срочной выдаче еды.'),
      talk('dren', 'Decide the fate of Dren and the salvaged stores.', 'Решить судьбу Дрена и спасённого груза.',
        'We saved twelve. Four drowned. I knew a ship would come, not whose children would sail on it. The stores can pay the sailors or feed this shore.',
        'Двенадцать спасены. Четверо утонули. Я знал, что придёт корабль, но не знал, чьи дети будут на нём. Запасами можно возместить морякам потери или накормить берег.',
        [
          action('wreck-restitution', 'Publish the truth and reserve salvage for survivors\' restitution.', 'Открыть правду и отдать груз на возмещение выжившим.',
            'The surviving sailors receive the salvage and Dren\'s confession. Saltcoast must ask openly for food instead of living on an unnamed wreck.',
            'Выжившие моряки получили груз и признание Дрена. Берегу придётся открыто просить еды, а не жить за счёт безымянной гибели.', { registry: 2, commons: -1 }),
          action('wreck-relief', 'Keep the food ashore; record the dead and compel Dren to rebuild the beacon.',
            'Оставить еду на берегу; записать погибших и обязать Дрена восстановить маяк.',
            'The shore keeps its food and promises a true light. The sailors receive names and an apology, not the goods that were theirs.',
            'Берег сохранил еду и обещал верный огонь. Моряки получили имена и извинение, но не свой груз.', { commons: 2, lanterns: 1, registry: -1 }),
        ]),
    ],
  },
  {
    id: 'ash-water', kind: 'side', requires: null, reward: 30,
    title: text('The Bitter Well', 'Горький колодец'),
    description: text('Cinderwell\'s furnaces pay wages and poison its water. The old Ash Cairn may reveal whether anyone knew.',
      'Печи Углеземья дают заработок и отравляют воду. Старый Пепельный курган может показать, знал ли об этом кто-нибудь.'),
    stages: [
      talk('tessa', 'Hear Tessa\'s warning in Cinderwell.', 'Выслушать предупреждение Тессы в Углеземье.',
        'The children\'s teeth stain gray. Beran calls it the soil; the soil did not start paying furnace wages last autumn. Look at the water marks on the cairn.',
        'У детей сереют зубы. Беран винит почву; но не почва прошлой осенью стала платить за печи. Посмотри на следы воды у кургана.',
        [action('ash-start', 'Examine the water channel at Ash Cairn.', 'Осмотреть водный канал у Пепельного кургана.',
          'Tessa suspects furnace runoff. The cairn marks an older, cleaner water channel.',
          'Тесса подозревает печной сток. У кургана отмечен старый канал с чистой водой.')]),
      inspect('ash-cairn', 'ash-channel', 'Inspect the sealed channel at Ash Cairn.', 'Осмотреть перекрытый канал Пепельного кургана.',
        'A stone warning predates the current furnaces. Opening the old channel would bypass the poison but flood the workers\' rented cellars.',
        'Каменное предупреждение старше нынешних печей. Старый канал обойдёт яд, но затопит подвалы, которые снимают рабочие.'),
      talk('tessa', 'Choose a remedy with Tessa.', 'Выбрать с Тессой выход.',
        'Close the furnaces and we lose our wages. Open the channel and we lose our rooms. There is no clean answer, only clean water someone must pay for.',
        'Закроем печи — потеряем заработок. Откроем канал — потеряем жильё. Чистого решения нет; есть чистая вода, за которую кто-то должен заплатить.',
        [
          action('ash-close', 'Close the furnaces until safe filtration is built.', 'Закрыть печи до устройства безопасной очистки.',
            'The furnaces cool and the water clears. The Commons must find winter work for families no longer earning their bread.',
            'Печи остыли, вода очистилась. Общины должны найти зимнюю работу семьям, лишившимся заработка.', { commons: 2, registry: -1 }),
          action('ash-channel-open', 'Open the clean channel and requisition empty Registry housing.', 'Открыть чистый канал и занять пустующее жильё палаты.',
            'The workers move into requisitioned offices while the furnaces keep paying. Displaced clerks wait beside the families their books once displaced.',
            'Рабочие заняли изъятые конторы, печи продолжают платить. Писцы ждут жилья рядом с семьями, которых когда-то выселили их книги.', { lanterns: 2, registry: -2 }),
        ]),
    ],
  },
  {
    id: 'bell-metal', kind: 'side', requires: null, reward: 35,
    title: text('The Metal That Remembers', 'Металл, который помнит'),
    description: text('Bell Foundry has an order for military fittings and a wall full of unpaid funeral bells. Decide what a conquered road should carry.',
      'На Колокольном дворе заказаны военные детали, а вдоль стены стоят неоплаченные поминальные колокола. Решить, что повезёт завоёванная дорога.'),
    stages: [
      talk('radek', 'Ask Radek at Bell Foundry about the silenced bells.', 'Расспросить Радека на Колокольном дворе об умолкших колоколах.',
        'The brass is pledged to the army. Each bell already has a dead person\'s name inside it. The tax vault says whether a promise to the dead outranks a purchase.',
        'Латунь заложена армии. В каждом колоколе уже вырезано имя покойного. Податное хранилище решит, что старше: обещание мёртвому или покупка.',
        [action('bell-start', 'Read the foundry lien in the Tax Vault.', 'Прочесть залог литейной в Податном хранилище.',
          'Radek cannot fill both orders. The military lien may have been bought with the mourners\' deposits.',
          'Радек не исполнит оба заказа. Военный залог могли оплатить задатками скорбящих.')]),
      inspect('tax-vault', 'bell-lien', 'Inspect the foundry lien at the Tax Vault.', 'Изучить залог литейной в Податном хранилище.',
        'The army used the funeral deposits to purchase the same brass twice. Radek signed because the advance kept his apprentices fed.',
        'Армия на поминальные задатки купила ту же латунь второй раз. Радек подписал: аванс кормил учеников.'),
      talk('radek', 'Choose what Bell Foundry will make.', 'Решить, что отольют на Колокольном дворе.',
        'Your convoy needs fittings. Their villages need the right to mourn. I can engrave the names on the fittings, but do not pretend that makes a bell.',
        'Твоему обозу нужны детали. Их деревням — право скорбеть. Я вырежу имена на деталях, но не притворяйся, что это колокол.',
        [
          action('bell-mourn', 'Cast the promised bells; expose the double purchase.', 'Отлить обещанные колокола; раскрыть двойную покупку.',
            'The funeral bells go home. Military procurement must find honest brass rather than requisitioning grief.',
            'Поминальные колокола отправились домой. Военному снабжению придётся искать честную латунь, а не изымать горе.', { commons: 2, registry: -1 }),
          action('bell-road', 'Make the road fittings and engrave a public memorial on every one.', 'Сделать дорожные детали и вырезать на каждой открытый памятный список.',
            'The fittings carry the names along the road. The mourners did not consent; their dead now serve a campaign they never chose.',
            'Детали понесут имена по дороге. Скорбящие не давали согласия; их мёртвые служат походу, которого не выбирали.', { registry: 2, commons: -1 }),
        ]),
    ],
  },
  {
    id: 'last-beacon', kind: 'side', requires: null, reward: 35,
    title: text('The Keeper\'s Last Watch', 'Последняя вахта смотрителя'),
    description: text('A frozen beacon marks a safe pass on maps that no longer match the snow. Someone continues collecting a dead keeper\'s pay.',
      'Замёрзший маяк отмечает безопасный перевал на устаревших картах. Кто-то до сих пор получает жалованье мёртвого смотрителя.'),
    stages: [
      talk('lev', 'Hear Lev at Star Monastery about the missing keeper.', 'Выслушать Льва в Звёздном монастыре о пропавшем смотрителе.',
        'The beacon report arrives every week in the same hand. Its keeper has been buried here since spring. I need to know who is keeping travelers alive in his name.',
        'Отчёт маяка приходит каждую неделю тем же почерком. Смотритель похоронен здесь с весны. Я должен узнать, кто под его именем спасает путников.',
        [action('beacon-start', 'Investigate Frozen Beacon.', 'Расследовать тайну Замёрзшего маяка.',
          'Lev suspects the keeper\'s reports are forged but does not want an occupied watch extinguished.',
          'Лев подозревает подлог отчётов, но не хочет погасить действующую вахту.')]),
      inspect('frozen-beacon', 'beacon-log', 'Inspect the watch log at Frozen Beacon.', 'Изучить вахтенный журнал Замёрзшего маяка.',
        'Three deserters share the watch and the dead man\'s wage. Their log records twenty-seven rescues and the names of the soldiers hunting them.',
        'Трое дезертиров делят вахту и жалованье покойного. В журнале — двадцать семь спасённых и имена солдат, которые их преследуют.'),
      talk('lev', 'Choose how the beacon keepers can remain at work.', 'Решить, как сохранить смотрителям маяка работу.',
        'Amnesty requires their real names. A new forgery keeps them hidden, but when one dies we will have to bury another stranger.',
        'Для помилования нужны настоящие имена. Новый подлог скроет их, но когда кто-то умрёт, нам снова придётся хоронить чужака.',
        [
          action('beacon-amnesty', 'Publish their rescues and grant named civilian amnesty.', 'Обнародовать спасения и дать именное гражданское помилование.',
            'The deserters become named civilian keepers. Officers resent the precedent; travelers finally know who keeps the light.',
            'Дезертиры стали именными гражданскими смотрителями. Офицеры недовольны; путники наконец знают, кто хранит огонь.', { commons: 2, registry: 1 }),
          action('beacon-hidden', 'Keep their identities hidden and pay the watch through the Lanterns.', 'Скрыть их имена и оплачивать вахту через фонарщиков.',
            'The watch continues under a dead name. The Lanterns keep the wages moving; the keepers remain unable to come home.',
            'Вахта продолжается под именем мёртвого. Фонарщики доставляют плату; смотрители по-прежнему не могут вернуться домой.', { lanterns: 2, registry: -1 }),
        ]),
    ],
  },
  {
    id: 'borrowed-name', kind: 'side', requires: null, reward: 35,
    title: text('A Name to Come Home In', 'Имя, в котором можно вернуться'),
    description: text('A survivor in Hollowvale wears another woman\'s name. Returning the truth may cost her the only family she has left.',
      'Выжившая в Пустодоле носит имя другой женщины. Возвращение правды может стоить ей последней семьи.'),
    stages: [
      talk('mila', 'Hear Mila in Hollow Village.', 'Выслушать Милу в Пустой деревне.',
        'The name on my ration token belongs to a woman who died on the road. Her mother thinks I am the daughter she lost in the fever. The well remembers both of us.',
        'Имя на моём жетоне принадлежит женщине, умершей в дороге. Её мать думает, что я дочь, которую она потеряла во время лихорадки. Колодец помнит нас обеих.',
        [action('borrowed-start', 'Find both name bowls at the Name Well.', 'Найти обе именные миски в Колодце имён.',
          'Mila took a dead woman\'s ration token to survive. She asks whether the original family left any record at the well.',
          'Мила выжила, взяв жетон умершей. Она просит узнать, оставила ли семья той женщины запись у колодца.')]),
      inspect('name-well', 'borrowed-bowls', 'Inspect the paired bowls at the Name Well.', 'Осмотреть парные миски Колодца имён.',
        'The mother left two bowls, one inscribed "my daughter" and one "the child who came back." She has known the truth for months.',
        'Мать оставила две миски: «моя дочь» и «ребёнок, который вернулся». Она знает правду уже несколько месяцев.'),
      talk('mila', 'Tell Mila what her mother left at the well.', 'Рассказать Миле, что её мать оставила у колодца.',
        'She knew. Then I have been lying to the book, not to her. Shall I demand my own name and risk losing our ration, or keep the one that brings us bread?',
        'Она знала. Значит, я лгала книге, а не ей. Требовать своё имя и рисковать нашим пайком — или оставить то, которое приносит хлеб?',
        [
          action('borrowed-restore', 'Restore both names and recognize the household\'s chosen kinship.', 'Восстановить оба имени и признать выбранное семьёй родство.',
            'Mila takes her own name and remains a daughter. Their household enters the books as chosen kin, not a clerical mistake.',
            'Мила вернула своё имя и осталась дочерью. Их семья записана как выбранное родство, а не ошибка писца.', { commons: 2, registry: 1 }),
          action('borrowed-keep', 'Keep the ration name private; let the family name itself.', 'Сохранить пайковое имя в тайне; пусть семья назовёт себя сама.',
            'The family keeps its private truth and its public disguise. Their bread is secure until another clerk starts asking questions.',
            'Семья сохранила свою правду и чужое имя для книг. Хлеб будет, пока новый писец не начнёт задавать вопросы.', { lanterns: 2, registry: -1 }),
        ]),
    ],
  },
];

export const NPCS: StoryNpc[] = [
  {
    id: 'mara', locationId: 'roadward', name: text('Mara Venn', 'Мара Венн'),
    role: text('Quartermaster without a seal', 'Интендант без печати'), faction: 'guard',
    activity: text('Counting returned grain sacks', 'Считает возвращённые мешки зерна'),
    greeting: text('A captured road is a promise to the people beside it. Empty villages make poor subjects and worse victories.',
      'Взятая дорога — обещание людям у обочины. Пустые деревни плохи и как подданные, и как победы.'),
    local: text('Capture the posts, break the raiding caravan, and supply two garrisons with your own convoy. That opens the fortress. It does not tell you what to do with the road afterward.',
      'Возьми заставы, разбей вражеский караван и снабди два гарнизона своим обозом. Это откроет крепость. Но не скажет, что потом делать с дорогой.'),
    belief: text('I served three banners. All three could count arrows. Only one bothered counting the people who made them.',
      'Я служила трём знамёнам. Все умели считать стрелы. Лишь одно удосужилось сосчитать тех, кто их делал.'),
  },
  {
    id: 'toman', locationId: 'greenhollow', name: text('Toman Reed', 'Томан Рид'),
    role: text('Erased village reeve', 'Староста стёртой деревни'), faction: 'elf',
    activity: text('Mending a mill shutter', 'Чинит ставню мельницы'),
    greeting: text('We are still here. You may need to say that twice to anyone carrying a ledger.', 'Мы ещё здесь. Любому с книгой учёта это лучше сказать дважды.'),
    local: text('Greenmarch fed the garrisons before the garrisons learned to demand receipts. The Old Orchard remembers longer than the Registry.',
      'Зелёный рубеж кормил гарнизоны ещё до того, как они научились требовать расписки. Старый сад помнит больше палаты.'),
    belief: text('I lied about grain to save seed. A small lie grew into an empty space where our village should be.',
      'Я солгал о зерне ради семян. Маленькая ложь выросла в пустое место там, где должна быть деревня.'),
  },
  {
    id: 'lida', locationId: 'greenhollow', name: text('Lida Ash', 'Лида Эш'),
    role: text('Orchard keeper', 'Хранительница сада'), faction: 'elf',
    activity: text('Grafting a young branch', 'Прививает молодую ветку'),
    greeting: text('Do not tie your horse to that sapling. It has already survived one occupation.', 'Не привязывай коня к саженцу. Одну оккупацию он уже пережил.'),
    local: text('At the orchard, names are cut into stone below the tax paint. Trees outlast the legal language wrapped around them.',
      'В саду под податной краской вырезаны имена. Деревья переживают правовые слова, которыми их обвивают.'),
    belief: text('Owning a thing and caring for it are not the same work. I wish the law paid more attention to the second.',
      'Владеть и заботиться — разная работа. Хотелось бы, чтобы закон чаще замечал вторую.'),
  },
  {
    id: 'yara', locationId: 'thornwatch', name: text('Yara of the Thorns', 'Яра Терновая'),
    role: text('Hunt warden', 'Хранительница охоты'), faction: 'elf',
    activity: text('Removing wire snares', 'Снимает проволочные силки'),
    greeting: text('Hunger has no hunting season. Patrols keep forgetting that.', 'У голода нет охотничьего сезона. Дозоры вечно это забывают.'),
    local: text('The Stag Shrine honors lost hunters. Families used to receive a share of winter meat; now only names with active tokens do.',
      'Оленье святилище чтит погибших охотников. Прежде семьям давали зимнее мясо; теперь — лишь тем, у кого действующий жетон.'),
    belief: text('A sacred oath that starves a child is only a rule with a prettier voice.', 'Священная клятва, от которой голодает ребёнок, — просто правило с красивым голосом.'),
  },
  {
    id: 'sella', locationId: 'mirecross', name: text('Sella Brine', 'Селла Брайн'),
    role: text('Archive diver', 'Ныряльщица архива'), faction: 'villain',
    activity: text('Drying brass rubbings', 'Сушит оттиски с латуни'),
    greeting: text('Mud keeps what officials throw away. The difficulty is making people read it afterward.',
      'Ил хранит то, что чиновники выбрасывают. Труднее заставить людей потом это прочесть.'),
    local: text('Fenlands ferries used to carry copies of every toll order. The Drowned Archive is downstream; Reed Chapel certified its duplicates.',
      'Болотные паромы возили копии каждого податного приказа. Затопленный архив ниже по реке; часовня заверяла дубликаты.'),
    belief: text('I charge for my work. Truth costs rope, dry clothes and sometimes a friend. Free truth usually means someone else paid.',
      'Я беру деньги за работу. Правда стоит верёвки, сухой одежды, иногда друга. Бесплатная правда обычно означает, что заплатил кто-то другой.'),
  },
  {
    id: 'ivet', locationId: 'reed-chapel', name: text('Sister Ivet', 'Сестра Ивета'),
    role: text('Chapel record keeper', 'Хранительница записей часовни'), faction: 'guard',
    activity: text('Portioning flour for the sick', 'Отмеряет муку больным'),
    greeting: text('We have beds for six and blankets for four. Judge me after you choose who goes outside.',
      'Коек шесть, одеял четыре. Суди меня после того, как выберешь, кому выйти наружу.'),
    local: text('We record those pulled from the river. At Lantern Ferry, ask Oss who was charged as cargo.',
      'Мы записываем тех, кого вытащили из реки. Спроси Осса на Фонарной переправе, кого обложили как груз.'),
    belief: text('Mercy that depends on another household going hungry is a debt, not a virtue. I still accepted it.',
      'Милосердие, зависящее от голода в чужом доме, — долг, а не добродетель. Я всё же его приняла.'),
  },
  {
    id: 'oss', locationId: 'lantern-ferry', name: text('Oss Vale', 'Осс Вейл'),
    role: text('Indebted ferryman', 'Паромщик-должник'), faction: 'villain',
    activity: text('Testing a frayed mooring rope', 'Проверяет истёртый причальный канат'),
    greeting: text('I know what the crossing costs. I am less certain what it is worth.', 'Я знаю, сколько стоит переправа. Не уверен, чего она стоит на самом деле.'),
    local: text('The Lantern Network carries people without papers. We are smugglers when the ink says so and rescuers when the ice breaks.',
      'Фонарщики перевозят людей без бумаг. По чернилам мы контрабандисты, по ломающемуся льду — спасатели.'),
    belief: text('A debt can make a coward of a decent person. It cannot make the cowardice decent.', 'Долг может сделать порядочного человека трусом. Порядочной трусость не станет.'),
  },
  {
    id: 'orsa', locationId: 'saltmarket', name: text('Orsa Flint', 'Орса Флинт'),
    role: text('Grain factor', 'Зерновая поверенная'), faction: 'guard',
    activity: text('Weighing grain against stone measures', 'Взвешивает зерно каменными гирями'),
    greeting: text('A receipt has no calories. I have been explaining this to officials all week.',
      'В расписке нет пищи. Всю неделю объясняю это чиновникам.'),
    local: text('Saltmarket trades in promises; the Tide Observatory measures ships. Wreckers\' Rest lives on what the sea refuses to deliver properly.',
      'Солёный рынок торгует обещаниями, обсерватория измеряет суда. Приют корабельщиков живёт тем, что море отказывается доставлять как положено.'),
    belief: text('Open stores feed anyone standing at the door. Ration books feed those still alive to be counted next month. Both leave someone outside.',
      'Открытые склады кормят стоящих у двери. Пайковые книги — тех, кто доживёт до следующего месяца. В обоих случаях кто-то снаружи.'),
  },
  {
    id: 'dren', locationId: 'wreckers-rest', name: text('Dren Silt', 'Дрен Силт'),
    role: text('Salvage captain', 'Старшина спасателей'), faction: 'villain',
    activity: text('Repairing a rescued sailor\'s boots', 'Чинит сапоги спасённого моряка'),
    greeting: text('If you are looking for villains, wait until you have heard the storm report.', 'Если ищешь злодеев, сперва выслушай рассказ о буре.'),
    local: text('Our boats could not get past the waves. We reached the wreck by ropes from shore. Ask the observatory which way its lantern pointed.',
      'Наши лодки не прошли волну. К обломкам добрались по канатам с берега. Спроси обсерваторию, куда светил её фонарь.'),
    belief: text('Saving someone after endangering them does not balance a scale. I keep mending the boots anyway.',
      'Спасение того, кого сам подверг опасности, не уравновешивает весы. Всё равно продолжаю чинить сапоги.'),
  },
  {
    id: 'hana', locationId: 'tide-observatory', name: text('Hana Pell', 'Хана Пелл'),
    role: text('Tide reader', 'Чтица приливов'), faction: 'elf',
    activity: text('Marking the falling tide', 'Отмечает убывающий прилив'),
    greeting: text('The sea is not honest. It is merely less interested in our excuses.', 'Море не честно. Ему просто меньше интересны наши оправдания.'),
    local: text('Inspect the weight records and the lantern mount yourself. The same instruments can expose missing grain and a deliberate wreck.',
      'Сам осмотри весовые записи и крепление фонаря. Одни приборы разоблачают и пропавшее зерно, и намеренное крушение.'),
    belief: text('An observer who refuses to testify is another kind of blind person.', 'Наблюдатель, отказывающийся свидетельствовать, — ещё один вид слепого.'),
  },
  {
    id: 'beran', locationId: 'cinderwell', name: text('Beran Coalhand', 'Беран Угольная Рука'),
    role: text('Glassmaster', 'Стекольный мастер'), faction: 'villain',
    activity: text('Cooling an unmarked debt seal', 'Остужает долговую печать без знака'),
    greeting: text('Glass remembers the shape it was forced into. People do too.', 'Стекло помнит форму, в которую его загнали. Люди тоже.'),
    local: text('Glass Quarry holds the debt molds. Ash Cairn marks the old water channel. Tessa knows what the furnaces cost beyond wages.',
      'В Стеклянной каменоломне долговые формы. Пепельный курган отмечает старый водный канал. Тесса знает цену печей помимо заработка.'),
    belief: text('I told myself a craftsman does not choose the use of his work. That was a useful lie for a man who liked being paid.',
      'Я говорил себе, что мастер не выбирает применение работе. Удобная ложь для того, кто любит получать плату.'),
  },
  {
    id: 'tessa', locationId: 'cinderwell', name: text('Tessa Rill', 'Тесса Рилл'),
    role: text('Well physician', 'Колодезная лекарка'), faction: 'elf',
    activity: text('Comparing two jars of well water', 'Сравнивает две банки колодезной воды'),
    greeting: text('Clean-looking water is not the same as clean water. Neither is a clean-looking law.',
      'Прозрачная вода не значит чистая. С прозрачным законом та же беда.'),
    local: text('The poison follows the furnace drains. At Ash Cairn there is an older channel; inspect it before promising anyone a cure.',
      'Яд идёт по печным стокам. У Пепельного кургана старый канал; изучи его, прежде чем обещать исцеление.'),
    belief: text('Do not ask whether I favor workers or children. They go home to the same tables.', 'Не спрашивай, за рабочих я или за детей. Они возвращаются к одним столам.'),
  },
  {
    id: 'vesk', locationId: 'crownbridge', name: text('Auditor Vesk', 'Ревизор Веск'),
    role: text('Author of the erasure decree', 'Автор указа о стирании'), faction: 'guard',
    activity: text('Reopening rejected petitions', 'Вновь открывает отклонённые прошения'),
    greeting: text('I can show you where the law failed. The more difficult page is the one where it worked exactly as written.',
      'Я покажу, где закон дал сбой. Труднее читать страницу, где он сработал точно так, как написан.'),
    local: text('The Tax Vault preserves the emergency decree and Bell Foundry\'s liens. Neither is protected from inspection now.',
      'Податное хранилище хранит чрезвычайный указ и залоги Колокольного двора. От осмотра они больше не защищены.'),
    belief: text('A signature can harm more people than a sword. It gives its owner less trouble sleeping, which is why we need witnesses.',
      'Подпись калечит больше людей, чем меч. Её владельцу легче спится — потому и нужны свидетели.'),
  },
  {
    id: 'radek', locationId: 'bell-foundry', name: text('Radek Noll', 'Радек Нолл'),
    role: text('Bell founder', 'Литейщик колоколов'), faction: 'guard',
    activity: text('Tracing a name inside a silent bell', 'Обводит имя внутри молчащего колокола'),
    greeting: text('Strike good brass and it tells you where it was thinned. I wish contracts did the same.',
      'Ударь по хорошей латуни — услышишь, где её истончили. Договоры бы так.'),
    local: text('Our military purchase and funeral deposits meet in one lien at the Tax Vault. Read it before telling me which order is sacred.',
      'Военный заказ и поминальные задатки сошлись в одном залоге Податного хранилища. Прочти, прежде чем объявлять один заказ священным.'),
    belief: text('A road has to carry grief as well as grain. Otherwise it only belongs to people with something to sell.',
      'Дорога должна везти и горе, и зерно. Иначе она принадлежит только тем, у кого есть что продать.'),
  },
  {
    id: 'nika', locationId: 'high-pass', name: text('Nika Frost', 'Ника Фрост'),
    role: text('Pass guide', 'Проводница перевала'), faction: 'elf',
    activity: text('Planting a new snow marker', 'Ставит новую снежную веху'),
    greeting: text('Up here a stranger is someone you have not had to dig out yet.', 'Здесь чужак — тот, кого ты ещё не выкапывал из снега.'),
    local: text('Star Monastery keeps travelers\' papers. Frozen Beacon keeps travelers alive. Only one of them has a respectable guest book.',
      'Звёздный монастырь хранит бумаги путников. Замёрзший маяк хранит самих путников. Приличная книга гостей есть лишь у одного.'),
    belief: text('I lend boots, not allegiances. People with different banners get frostbite in the same places.',
      'Я одалживаю сапоги, не верность. Под разными знамёнами отмораживают одни и те же места.'),
  },
  {
    id: 'lev', locationId: 'star-monastery', name: text('Brother Lev', 'Брат Лев'),
    role: text('Keeper of the first census', 'Хранитель первой переписи'), faction: 'guard',
    activity: text('Copying a traveler\'s uncensored name', 'Переписывает невычеркнутое имя путника'),
    greeting: text('We kept the census safe and failed to keep its courier warm. Preservation is not always kindness.',
      'Мы сберегли перепись и не согрели её гонца. Сохранность не всегда означает доброту.'),
    local: text('The original census lies open here for inspection. The beacon\'s false reports are a different problem, and perhaps a kinder one.',
      'Подлинная перепись открыта здесь для осмотра. Ложные отчёты маяка — другая беда, возможно, более добрая.'),
    belief: text('A name is not proof of worth. It is a way to ask someone to answer.', 'Имя не доказывает достоинства. Оно позволяет попросить человека ответить.'),
  },
  {
    id: 'ada', locationId: 'hollow-village', name: text('Ada Wren', 'Ада Ренн'),
    role: text('Last elected speaker', 'Последняя выборная староста'), faction: 'elf',
    activity: text('Setting bowls at an empty table', 'Расставляет миски на пустом столе'),
    greeting: text('You can win a battle in an afternoon. Try persuading a road to remember us.',
      'Битву можно выиграть за день. Попробуй убедить дорогу вспомнить нас.'),
    local: text('The Name Well holds the names the Registry refused. The Last Archive holds the index that made refusal profitable.',
      'Колодец хранит имена, отвергнутые палатой. Последний архив — указатель, который сделал отказ выгодным.'),
    belief: text('Ask who will be allowed to disagree with you after you win. That is the shape of the peace you are making.',
      'Спроси, кому будет позволено спорить с тобой после победы. Таков будет мир, который ты строишь.'),
  },
  {
    id: 'mila', locationId: 'hollow-village', name: text('Mila, by choice', 'Мила, по выбору'),
    role: text('Survivor with a borrowed name', 'Выжившая под чужим именем'), faction: 'villain',
    activity: text('Stitching two family cloths together', 'Сшивает две семейные ткани'),
    greeting: text('I have been called a fraud by people who never asked what I lost.', 'Меня называли обманщицей люди, ни разу не спросившие, что я потеряла.'),
    local: text('The Name Well keeps bowls for the absent. Sometimes two bowls tell more truth than one official token.',
      'В Колодце имён хранят миски отсутствующих. Иногда две миски правдивее одного официального жетона.'),
    belief: text('Family can be a choice made after everything else has been taken. I would like the books to learn that.',
      'Семья бывает выбором, сделанным после потери всего остального. Я бы хотела, чтобы книги это усвоили.'),
  },
  {
    id: 'elin', locationId: 'last-archive', name: text('Elin Voss', 'Элин Восс'),
    role: text('Custodian of the master index', 'Хранитель главного указателя'), faction: 'guard',
    activity: text('Preparing blank pages for witnesses', 'Готовит чистые страницы свидетелям'),
    greeting: text('I can hand you the pen. I cannot make it an innocent object.', 'Я могу дать тебе перо. Сделать его невинным предметом не могу.'),
    local: text('Inspect the master index before deciding anything. Finish the investigations across the borderland. Secure two supplied posts and destroy the raiding caravan; a promise needs a road that can carry it.',
      'Прежде решения изучи указатель. Закончи расследования по пограничью. Снабди две взятые заставы и разбей вражеский караван: обещанию нужна дорога, способная его нести.'),
    belief: text('You may leave the final page blank while you help people elsewhere. When you choose, it binds the road; victory still requires the fortress commander\'s defeat.',
      'Последнюю страницу можно оставить пустой, пока помогаешь другим. Выбор свяжет дорогу; для победы ещё нужно победить командира крепости.'),
  },
  {
    id: 'ren', locationId: 'roadward', name: text('Ren the Cartwright', 'Рен Тележник'),
    role: text('Convoy route keeper', 'Хранитель путей обоза'), faction: 'villain',
    activity: text('Checking convoy wheel pins', 'Проверяет колёсные чеки обоза'),
    greeting: text('Your cart is part of your promise. Do not ride ahead and call its wreck an acceptable loss.',
      'Телега — часть твоего обещания. Не уезжай вперёд, называя её обломки допустимой потерей.'),
    local: text('Fast travel requires a discovered road stop, a nearby healthy convoy and no nearby enemies or incoming missiles at either end. It carries both of you, not cargo out of danger. Repair the cart by holding interact beside it.',
      'Быстрый переезд требует открытой дорожной стоянки, здорового обоза рядом и отсутствия врагов и летящих снарядов на обоих концах. Он перевозит вас обоих, а не спасает груз от боя. Для ремонта удерживай взаимодействие у телеги.'),
    belief: text('Military banners tell travelers who claims a road. Wheel tracks tell them whether anyone can actually use it.',
      'Военные знамёна говорят, кто претендует на дорогу. Колеи говорят, может ли кто-то ею пользоваться.'),
  },
];
